In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("data/TuragOr.csv")

In [124]:
df

,Date,TempA,TempB,TempC,TempD,pHA,pHB,pHC,pHD,EC_A,...,DO_C,DO_D,BOD_A,BOD_B,BOD_C,BOD_D,TN_A,TN_B,TN_C,TN_D
0,15-Dec-21,21.5,21.2,21.3,21.4,7.73,8.12,7.91,8.48,1748,...,2.60,2.59,27.96,27.70,27.88,27.93,1.28,1.25,1.26,1.27
1,30-Dec-21,21.0,20.8,20.5,20.7,7.82,8.06,8.12,8.35,1832,...,2.77,2.71,27.59,27.21,26.48,27.00,1.06,1.10,1.08,1.11
2,15-Jan-22,20.5,20.2,20.3,20.2,7.95,8.04,8.29,8.40,2049,...,2.83,2.85,26.48,25.17,25.56,25.00,0.76,0.75,0.79,0.77
3,30-Jan-22,20.3,20.0,20.1,19.9,8.17,8.11,8.22,8.43,2105,...,2.86,2.89,25.55,23.86,24.10,24.79,0.95,0.93,0.94,0.94
4,15-Feb-22,21.0,20.6,21.1,20.9,8.26,8.17,8.25,8.49,1855,...,2.63,2.68,27.59,27.14,27.61,27.74,1.05,1.00,1.09,1.10
5,28-Feb-22,21.8,22.0,21.7,21.5,8.49,8.33,8.32,8.56,1809,...,2.53,2.54,28.13,28.49,28.00,28.09,1.29,1.35,1.22,1.25
6,15-Mar-22,24.9,24.6,24.8,24.7,8.02,7.98,8.10,8.17,1796,...,2.03,2.03,31.52,30.00,30.25,30.14,1.95,1.72,1.70,1.63
7,30-Mar-22,26.8,26.9,27.0,26.9,7.32,7.65,7.68,7.83,1813,...,1.65,1.70,32.40,32.53,32.79,32.54,2.05,1.98,2.11,2.03
8,15-Apr-22,29.1,28.9,29.3,29.7,6.83,6.91,7.12,7.35,1914,...,0.66,0.71,38.17,38.00,38.55,38.29,2.87,2.78,2.85,2.80
9,30-Apr-22,31.7,31.5,31.2,31.3,6.22,6.35,6.37,6.29,1928,...,0.11,0.13,41.53,41.24,40.83,40.55,3.23,3.21,3.14,3.10
10,15-May-22,33.1,32.7,32.9,32.8,6.30,6.42,6.25,6.18,1609,...,0.02,0.03,43.52,43.11,43.00,42.91,3.70,3.65,3.60,3.42
11,30-May-22,32.6,32.2,32.3,32.1,6.41,6.52,6.16,6.11,1554,...,0.05,0.06,42.87,42.14,42.71,42.14,3.35,3.30,3.29,3.27
12,15-Jun-22,30.4,30.5,30.3,30.1,6.56,6.47,6.33,6.19,1329,...,0.38,0.43,39.30,39.47,39.24,39.00,3.05,2.98,2.95,2.90
13,30-Jun-22,28.7,28.9,28.4,28.1,6.98,7.05,6.88,6.76,1257,...,0.95,1.00,38.12,37.65,37.38,36.51,2.65,2.61,2.60,2.55
14,15-Jul-22,28.3,28.1,27.9,27.9,7.11,7.15,7.20,7.14,1157,...,1.02,1.03,35.70,37.35,36.50,35.74,2.47,2.36,2.29,2.17
15,30-Jul-22,27.5,27.8,27.2,27.1,7.23,7.22,7.30,7.26,1122,...,1.36,1.44,34.23,35.79,33.10,32.97,2.15,2.14,2.11,2.20
16,15-Aug-22,26.8,27.0,26.4,26.2,7.15,7.19,7.22,7.10,1052,...,1.91,1.94,32.40,32.75,32.15,32.10,2.11,2.14,2.06,2.09
17,30-Aug-22,26.3,26.5,26.2,26.1,7.12,7.13,7.29,7.14,1033,...,1.94,1.95,32.11,32.31,32.19,32.07,1.97,1.89,2.01,1.98
18,15-Sep-22,24.9,24.8,25.3,25.0,7.29,7.38,7.32,7.25,951,...,1.97,1.98,31.52,31.69,32.00,31.86,1.87,1.89,2.01,1.98
19,30-Sep-22,24.2,24.3,24.7,24.5,7.45,7.69,7.36,7.39,958,...,2.03,2.05,29.75,29.96,30.27,30.10,1.55,1.59,1.68,1.88
20,15-Oct-22,23.7,23.2,23.5,23.1,7.51,7.88,7.49,7.51,1128,...,2.15,2.19,29.63,29.52,29.61,29.50,1.62,1.59,1.55,1.49
21,30-Oct-22,23.1,22.8,23.0,22.6,7.59,7.92,7.63,7.55,1369,...,2.24,2.30,29.50,29.07,29.10,29.00,1.28,1.21,1.23,1.15
22,15-Nov-22,22.6,22.1,22.4,22.0,7.60,7.93,7.65,7.56,1512,...,2.33,2.41,29.18,28.76,28.95,28.33,1.18,1.23,1.34,1.27
23,30-Nov-22,22.0,21.7,21.9,21.8,7.69,7.95,7.68,8.11,1627,...,2.49,2.50,28.30,28.00,28.17,28.14,1.27,1.26,1.17,1.29

In [125]:
df.columns

Index(['Date', 'TempA', 'TempB', 'TempC', 'TempD', 'pHA', 'pHB', 'pHC', 'pHD',
       'EC_A', 'EC_B', 'EC_C', 'EC_D', 'DO_A', 'DO_B', 'DO_C', 'DO_D', 'BOD_A',
       'BOD_B', 'BOD_C', 'BOD_D', 'TN_A', 'TN_B', 'TN_C', 'TN_D'],
      dtype='object')

In [76]:
df.describe()

,TempA,TempB,TempC,TempD,pHA,pHB,pHC,pHD,EC_A,EC_B,...,DO_C,DO_D,BOD_A,BOD_B,BOD_C,BOD_D,TN_A,TN_B,TN_C,TN_D
count,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,...,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000
mean,25.533333,25.387500,25.404167,25.275000,7.366667,7.484167,7.422500,7.483333,1521.125000,1544.166667,...,1.729583,1.755833,32.627083,32.454583,32.350833,32.185000,1.946250,1.912917,1.919583,1.901667
std,3.977946,4.034128,3.945220,3.980523,0.615126,0.625536,0.662251,0.790353,369.459689,326.482128,...,0.933849,0.929212,5.362345,5.572027,5.468787,5.295447,0.840175,0.821200,0.807468,0.778609
min,20.300000,20.000000,20.100000,19.900000,6.220000,6.350000,6.160000,6.110000,951.000000,952.000000,...,0.020000,0.030000,25.550000,23.860000,24.100000,24.790000,0.760000,0.750000,0.790000,0.770000
25%,21.950000,21.925000,21.850000,21.725000,7.077500,7.110000,7.180000,7.130000,1149.750000,1313.000000,...,1.002500,1.022500,28.257500,28.367500,28.127500,28.127500,1.277500,1.245000,1.227500,1.265000
50%,24.900000,24.700000,25.050000,24.850000,7.385000,7.670000,7.425000,7.450000,1581.500000,1628.000000,...,2.000000,2.005000,31.520000,30.845000,31.135000,31.000000,1.910000,1.805000,1.855000,1.930000
75%,28.400000,28.300000,28.025000,27.950000,7.752500,7.995000,7.957500,8.215000,1817.750000,1755.750000,...,2.500000,2.510000,36.305000,37.425000,36.720000,35.932500,2.515000,2.422500,2.367500,2.287500
max,33.100000,32.700000,32.900000,32.800000,8.490000,8.330000,8.320000,8.560000,2105.000000,2168.000000,...,2.860000,2.890000,43.520000,43.110000,43.000000,42.910000,3.700000,3.650000,3.600000,3.420000

In [20]:
temp = df[["TempA", "TempB", "TempC", "TempD"]]
pH   = df[["pHA", "pHB", "pHC", "pHD"]]
ec   = df[["EC_A", "EC_B", "EC_C", "EC_D"]]
do   = df[["DO_A", "DO_B", "DO_C", "DO_D"]]
bod  = df[["BOD_A", "BOD_B", "BOD_C", "BOD_D"]]
tn = df[["TN_A", "TN_B", "TN_C", "TN_D"]]

In [21]:
temp.head()

   TempA  TempB  TempC  TempD
0   21.5   21.2   21.3   21.4
1   21.0   20.8   20.5   20.7
2   20.5   20.2   20.3   20.2
3   20.3   20.0   20.1   19.9
4   21.0   20.6   21.1   20.9

In [79]:
temp.describe()

           TempA      TempB      TempC      TempD
count  24.000000  24.000000  24.000000  24.000000
mean   25.533333  25.387500  25.404167  25.275000
std     3.977946   4.034128   3.945220   3.980523
min    20.300000  20.000000  20.100000  19.900000
25%    21.950000  21.925000  21.850000  21.725000
50%    24.900000  24.700000  25.050000  24.850000
75%    28.400000  28.300000  28.025000  27.950000
max    33.100000  32.700000  32.900000  32.800000

In [80]:
#temp.loc[20:21] = [[2, 3, 4,5],[5,4,3,2]]  
#temp.index = temp.index + 1  
#temp = temp.sort_index()  
#temp

In [81]:
temp

    TempA  TempB  TempC  TempD
0    21.5   21.2   21.3   21.4
1    21.0   20.8   20.5   20.7
2    20.5   20.2   20.3   20.2
3    20.3   20.0   20.1   19.9
4    21.0   20.6   21.1   20.9
5    21.8   22.0   21.7   21.5
6    24.9   24.6   24.8   24.7
7    26.8   26.9   27.0   26.9
8    29.1   28.9   29.3   29.7
9    31.7   31.5   31.2   31.3
10   33.1   32.7   32.9   32.8
11   32.6   32.2   32.3   32.1
12   30.4   30.5   30.3   30.1
13   28.7   28.9   28.4   28.1
14   28.3   28.1   27.9   27.9
15   27.5   27.8   27.2   27.1
16   26.8   27.0   26.4   26.2
17   26.3   26.5   26.2   26.1
18   24.9   24.8   25.3   25.0
19   24.2   24.3   24.7   24.5
20   23.7   23.2   23.5   23.1
21   23.1   22.8   23.0   22.6
22   22.6   22.1   22.4   22.0
23   22.0   21.7   21.9   21.8

In [82]:
np.random.uniform(21, 21.5, 2)

array([21.08567965, 21.03327379])

In [22]:
tempa_mat = []

i=0
while i < len(temp["TempA"]) - 1:
    if temp["TempA"][i] < temp["TempA"][i+1]:
        val = np.random.uniform(temp["TempA"][i+1], temp["TempA"][i], 14)
        tempa_mat.append(val)
    
    val = np.random.uniform(temp["TempA"][i], temp["TempA"][i+1], 14)
    tempa_mat.append(val)
    
    i+=1

In [23]:
tempa_mat[0].min(),tempa_mat[0].max()

(21.026850468703923, 21.46830133701039)

In [24]:
tempa_mat[2].min(),tempa_mat[2].max()

(20.303820001887082, 20.48651032528013)

In [25]:
df.columns

Index(['Date', 'TempA', 'TempB', 'TempC', 'TempD', 'pHA', 'pHB', 'pHC', 'pHD',
       'EC_A', 'EC_B', 'EC_C', 'EC_D', 'DO_A', 'DO_B', 'DO_C', 'DO_D', 'BOD_A',
       'BOD_B', 'BOD_C', 'BOD_D', 'TN_A', 'TN_B', 'TN_C', 'TN_D'],
      dtype='object')

In [87]:
def data_gen(df):
    paramA = ["TempA", "pHA", "EC_A", "DO_A", "BOD_A", "TN_A"]
    paramB = ["TempB", "pHB", "EC_B", "DO_B", "BOD_B", "TN_B"]
    paramC = ["TempC", "pHC", "EC_C", "DO_C", "BOD_C", "TN_C"]
    paramD = ["TempD", "pHD", "EC_D", "DO_D", "BOD_D", "TN_D"]
    

    
    tempA_mat,tempB_mat,tempC_mat,tempD_mat,pHA_mat,pHB_mat,pHC_mat,pHD_mat,ECA_mat,ECB_mat,ECC_mat,ECD_mat,DOA_mat,DOB_mat,DOC_mat,DOD_mat,BODA_mat,BODB_mat,BODC_mat,BODD_mat,TNA_mat, TNB_mat, TNC_mat, TND_mat = val_append(df, paramA, paramB, paramC, paramD, i )
    
    return tempA_mat,tempB_mat,tempC_mat,tempD_mat,pHA_mat,pHB_mat,pHC_mat,pHD_mat,ECA_mat,ECB_mat,ECC_mat,ECD_mat,DOA_mat,DOB_mat,DOC_mat,DOD_mat,BODA_mat,BODB_mat,BODC_mat,BODD_mat,TNA_mat, TNB_mat, TNC_mat, TND_mat

        

        
        
def val_append(df, paramA, paramB, paramC, paramD, i):
    
    
    tempA_mat = []
    tempB_mat = []
    tempC_mat = []
    tempD_mat = []

    pHA_mat = []
    pHB_mat = []
    pHC_mat = []
    pHD_mat = []
    
    ECA_mat = []
    ECB_mat = []
    ECC_mat = []
    ECD_mat = []
    
    DOA_mat = []
    DOB_mat = []
    DOC_mat = []
    DOD_mat = []

    BODA_mat = []
    BODB_mat = []
    BODC_mat = []
    BODD_mat = []
    
    TNA_mat = []
    TNB_mat = []
    TNC_mat = []
    TND_mat = []

    
    i = 0
    while i < len(temp["TempA"]) - 1:
    
    #temp
    
        if df[paramA[0]][i] < df[paramA[0]][i+1]:
                val = np.random.uniform(df[paramA[0]][i+1], df[paramA[0]][i], 15)
                tempA_mat.append(val)
        else:
            val = np.random.uniform(df[paramA[0]][i], df[paramA[0]][i+1], 15)
            tempA_mat.append(val)

        if df[paramB[0]][i] < df[paramB[0]][i+1]:
                val = np.random.uniform(df[paramB[0]][i+1], df[paramB[0]][i], 15)
                tempB_mat.append(val)
        else:
            val = np.random.uniform(df[paramB[0]][i], df[paramB[0]][i+1], 15)
            tempB_mat.append(val)

        if df[paramC[0]][i] < df[paramC[0]][i+1]:
                val = np.random.uniform(df[paramC[0]][i+1], df[paramC[0]][i], 15)
                tempC_mat.append(val)
        else:
            val = np.random.uniform(df[paramC[0]][i], df[paramC[0]][i+1], 15)
            tempC_mat.append(val)

        if df[paramD[0]][i] < df[paramD[0]][i+1]:
                val = np.random.uniform(df[paramD[0]][i+1], df[paramD[0]][i], 15)
                tempD_mat.append(val)
        else:
            val = np.random.uniform(df[paramD[0]][i], df[paramD[0]][i+1], 15)
            tempD_mat.append(val)


        #pH

        if df[paramA[1]][i] < df[paramA[1]][i+1]:
                val = np.random.uniform(df[paramA[1]][i+1], df[paramA[1]][i], 15)
                pHA_mat.append(val)
        else:
            val = np.random.uniform(df[paramA[1]][i], df[paramA[1]][i+1], 15)
            pHA_mat.append(val)

        if df[paramB[1]][i] < df[paramB[1]][i+1]:
                val = np.random.uniform(df[paramB[1]][i+1], df[paramB[1]][i], 15)
                pHB_mat.append(val)
        else:
            val = np.random.uniform(df[paramB[1]][i], df[paramB[1]][i+1], 15)
            pHB_mat.append(val)

        if df[paramC[1]][i] < df[paramC[1]][i+1]:
                val = np.random.uniform(df[paramC[1]][i+1], df[paramC[1]][i], 15)
                pHC_mat.append(val)
        else:
            val = np.random.uniform(df[paramC[1]][i], df[paramC[1]][i+1], 15)
            pHC_mat.append(val)

        if df[paramD[1]][i] < df[paramD[1]][i+1]:
                val = np.random.uniform(df[paramD[1]][i+1], df[paramD[1]][i], 15)
                pHD_mat.append(val)
        else:
            val = np.random.uniform(df[paramD[1]][i], df[paramD[1]][i+1], 15)
            pHD_mat.append(val)

        #EC

        if df[paramA[2]][i] < df[paramA[2]][i+1]:
                val = np.random.uniform(df[paramA[2]][i+1], df[paramA[2]][i], 15)
                ECA_mat.append(val)
        else:
            val = np.random.uniform(df[paramA[2]][i], df[paramA[2]][i+1], 15)
            ECA_mat.append(val)

        if df[paramB[2]][i] < df[paramB[2]][i+1]:
                val = np.random.uniform(df[paramB[2]][i+1], df[paramB[2]][i], 15)
                ECB_mat.append(val)
        else:
            val = np.random.uniform(df[paramB[2]][i], df[paramB[2]][i+1], 15)
            ECB_mat.append(val)

        if df[paramC[2]][i] < df[paramC[2]][i+1]:
                val = np.random.uniform(df[paramC[2]][i+1], df[paramC[2]][i], 15)
                ECC_mat.append(val)
        else:
            val = np.random.uniform(df[paramC[2]][i], df[paramC[2]][i+1], 15)
            ECC_mat.append(val)

        if df[paramD[2]][i] < df[paramD[2]][i+1]:
                val = np.random.uniform(df[paramD[2]][i+1], df[paramD[2]][i], 15)
                ECD_mat.append(val)
        else:
            val = np.random.uniform(df[paramD[2]][i], df[paramD[2]][i+1], 15)
            ECD_mat.append(val)


        #DO

        if df[paramA[3]][i] < df[paramA[3]][i+1]:
                val = np.random.uniform(df[paramA[3]][i+1], df[paramA[3]][i], 15)
                DOA_mat.append(val)
        else:
            val = np.random.uniform(df[paramA[3]][i], df[paramA[3]][i+1], 15)
            DOA_mat.append(val)

        if df[paramB[3]][i] < df[paramB[3]][i+1]:
                val = np.random.uniform(df[paramB[3]][i+1], df[paramB[3]][i], 15)
                DOB_mat.append(val)
        else:
            val = np.random.uniform(df[paramB[3]][i], df[paramB[3]][i+1], 15)
            DOB_mat.append(val)

        if df[paramC[3]][i] < df[paramC[3]][i+1]:
                val = np.random.uniform(df[paramC[3]][i+1], df[paramC[3]][i], 15)
                DOC_mat.append(val)
        else:
            val = np.random.uniform(df[paramC[3]][i], df[paramC[3]][i+1], 15)
            DOC_mat.append(val)

        if df[paramD[3]][i] < df[paramD[3]][i+1]:
                val = np.random.uniform(df[paramD[3]][i+1], df[paramD[3]][i], 15)
                DOD_mat.append(val)
        else:
            val = np.random.uniform(df[paramD[3]][i], df[paramD[3]][i+1], 15)
            DOD_mat.append(val)



        #BOD

        if df[paramA[4]][i] < df[paramA[4]][i+1]:
                val = np.random.uniform(df[paramA[4]][i+1], df[paramA[4]][i], 15)
                BODA_mat.append(val)
        else:
            val = np.random.uniform(df[paramA[4]][i], df[paramA[4]][i+1], 15)
            BODA_mat.append(val)

        if df[paramB[4]][i] < df[paramB[4]][i+1]:
                val = np.random.uniform(df[paramB[4]][i+1], df[paramB[4]][i], 15)
                BODB_mat.append(val)
        else:
            val = np.random.uniform(df[paramB[4]][i], df[paramB[4]][i+1], 15)
            BODB_mat.append(val)

        if df[paramC[4]][i] < df[paramC[4]][i+1]:
                val = np.random.uniform(df[paramC[4]][i+1], df[paramC[4]][i], 15)
                BODC_mat.append(val)
        else:
            val = np.random.uniform(df[paramC[4]][i], df[paramC[4]][i+1], 15)
            BODC_mat.append(val)

        if df[paramD[4]][i] < df[paramD[4]][i+1]:
                val = np.random.uniform(df[paramD[4]][i+1], df[paramD[4]][i], 15)
                BODD_mat.append(val)
        else:
            val = np.random.uniform(df[paramD[4]][i], df[paramD[4]][i+1], 15)
            BODD_mat.append(val)


        #TN

        if df[paramA[5]][i] < df[paramA[5]][i+1]:
                val = np.random.uniform(df[paramA[5]][i+1], df[paramA[5]][i], 15)
                TNA_mat.append(val)
        else:
            val = np.random.uniform(df[paramA[5]][i], df[paramA[5]][i+1], 15)
            TNA_mat.append(val)

        if df[paramB[5]][i] < df[paramB[5]][i+1]:
                val = np.random.uniform(df[paramB[5]][i+1], df[paramB[5]][i], 15)
                TNB_mat.append(val)
        else:
            val = np.random.uniform(df[paramB[5]][i], df[paramB[5]][i+1], 15)
            TNB_mat.append(val)

        if df[paramC[5]][i] < df[paramC[5]][i+1]:
                val = np.random.uniform(df[paramC[5]][i+1], df[paramC[5]][i], 15)
                TNC_mat.append(val)
        else:
            val = np.random.uniform(df[paramC[5]][i], df[paramC[5]][i+1], 15)
            TNC_mat.append(val)

        if df[paramD[5]][i] < df[paramD[5]][i+1]:
                val = np.random.uniform(df[paramD[5]][i+1], df[paramD[5]][i], 15)
                TND_mat.append(val)
        else:
            val = np.random.uniform(df[paramD[5]][i], df[paramD[5]][i+1], 15)
            TND_mat.append(val)

        i+=1
    
    return tempA_mat,tempB_mat,tempC_mat,tempD_mat,pHA_mat,pHB_mat,pHC_mat,pHD_mat,ECA_mat,ECB_mat,ECC_mat,ECD_mat,DOA_mat,DOB_mat,DOC_mat,DOD_mat,BODA_mat,BODB_mat,BODC_mat,BODD_mat,TNA_mat, TNB_mat, TNC_mat, TND_mat

In [88]:
tempA_mat,tempB_mat,tempC_mat,tempD_mat,pHA_mat,pHB_mat,pHC_mat,pHD_mat,ECA_mat,ECB_mat,ECC_mat,ECD_mat,DOA_mat,DOB_mat,DOC_mat,DOD_mat,BODA_mat,BODB_mat,BODC_mat,BODD_mat,TNA_mat, TNB_mat, TNC_mat, TND_mat = data_gen(df)

In [89]:
tempA_list = []
tempB_list = []
tempC_list = []
tempD_list = []

pHA_list = []
pHB_list = []
pHC_list = []
pHD_list = []

ECA_list = []
ECB_list = []
ECC_list = []
ECD_list = []

DOA_list = []
DOB_list = []
DOC_list = []
DOD_list = []

BODA_list = []
BODB_list = []
BODC_list = []
BODD_list = []

TNA_list = []
TNB_list = []
TNC_list = []
TND_list = []


i=0
while i< len(tempA_mat):
    tempA_list.append(tempA_mat[i].tolist())
    tempB_list.append(tempB_mat[i].tolist())
    tempC_list.append(tempC_mat[i].tolist())
    tempD_list.append(tempD_mat[i].tolist())
    
    pHA_list.append(pHA_mat[i].tolist())
    pHB_list.append(pHB_mat[i].tolist())
    pHC_list.append(pHC_mat[i].tolist())
    pHD_list.append(pHD_mat[i].tolist())
    
    ECA_list.append(ECA_mat[i].tolist())
    ECB_list.append(ECB_mat[i].tolist())
    ECC_list.append(ECC_mat[i].tolist())
    ECD_list.append(ECD_mat[i].tolist())
    
    DOA_list.append(DOA_mat[i].tolist())
    DOB_list.append(DOB_mat[i].tolist())
    DOC_list.append(DOC_mat[i].tolist())
    DOD_list.append(DOD_mat[i].tolist())
    
    BODA_list.append(BODA_mat[i].tolist())
    BODB_list.append(BODB_mat[i].tolist())
    BODC_list.append(BODC_mat[i].tolist())
    BODD_list.append(BODD_mat[i].tolist())
    
    TNA_list.append(TNA_mat[i].tolist())
    TNB_list.append(TNB_mat[i].tolist())
    TNC_list.append(TNC_mat[i].tolist())
    TND_list.append(TND_mat[i].tolist())
    
    
    i += 1

tempA_list

[[21.20619169199319,
  21.210902468590238,
  21.257416475726465,
  21.093704869879527,
  21.20844155436343,
  21.448270144069557,
  21.228976703133487,
  21.015191755577792,
  21.2503309740264,
  21.331753928970205,
  21.070343034615306,
  21.47695308574595,
  21.46012376385791,
  21.172848197043635,
  21.346330516729868],
 [20.89339891590937,
  20.553093843029206,
  20.84013269063882,
  20.947527545042416,
  20.72837897032652,
  20.766414243939717,
  20.706632234439414,
  20.832312996915753,
  20.78268996964264,
  20.94693516044031,
  20.652473200296647,
  20.717388094519812,
  20.812309793278718,
  20.66792430039754,
  20.983164143926324],
 [20.359393123338613,
  20.472738988802867,
  20.432174644396653,
  20.37756208346038,
  20.38035546754564,
  20.45862972893119,
  20.407704975830168,
  20.476708310975706,
  20.350422919078465,
  20.344439203765624,
  20.393503352642494,
  20.38905356661099,
  20.300157032633216,
  20.34150798893364,
  20.39747278319335],
 [20.924390322524697,
  20.953832907791053,
  20.776235658313627,
  20.558153000802623,
  20.710097273593746,
  20.404765561915458,
  20.383632486540122,
  20.46086874578573,
  20.659353445367483,
  20.964541317619997,
  20.36251303546245,
  20.795169936755613,
  20.927156265853085,
  20.321111530774857,
  20.319417785685527],
 [21.249288453525644,
  21.527634811223585,
  21.187027679990862,
  21.524501769188674,
  21.240873423012168,
  21.33851071311586,
  21.092604773297147,
  21.033698834706904,
  21.668216539960298,
  21.123518000766808,
  21.291384178135523,
  21.684437760544753,
  21.738416047787364,
  21.600599275464916,
  21.473564418131136],
 [23.514003026091835,
  22.545369937171856,
  21.86040327038208,
  24.439886597846517,
  23.301225081738558,
  22.614765033513603,
  24.67230950443222,
  23.961030639255323,
  23.8244775309247,
  23.11047840362195,
  22.51659290210921,
  23.493657098742027,
  22.763258722284938,
  22.53332468033643,
  23.415675722322657],
 [26.054054657234108,
  26.27872148186867,
  25.426567100763847,
  26.106223202718887,
  26.74905199070209,
  26.746923329662575,
  26.64726282813796,
  25.933044773691087,
  25.148338866086974,
  25.399630493803535,
  25.231904903530275,
  26.10136930131427,
  25.856170220567254,
  26.404339116528096,
  26.65242597937054],
 [28.56666112278993,
  28.03320687586323,
  28.817830719668386,
  29.077458440831062,
  28.456047107118327,
  27.258264155940015,
  28.173020696925256,
  27.09630643513903,
  28.38473747735362,
  27.317081396878848,
  29.04441177251022,
  28.763197104292164,
  27.39737259954723,
  28.275259356081484,
  28.138991031224645],
 [29.555436866798004,
  31.00388931072354,
  29.895410761639177,
  31.354590841032785,
  30.65000452417714,
  29.291333000780348,
  30.546057523621997,
  31.645341322096602,
  30.21080175029885,
  30.260468391796877,
  31.4956612227705,
  30.289629457891767,
  29.598054744663287,
  31.24703990920312,
  31.185084677088206],
 [32.14930079833841,
  32.03587404987937,
  33.06034833113435,
  32.01915877376624,
  31.93060618894879,
  32.146402808573775,
  32.46993229124238,
  31.799907066977283,
  32.22161782155405,
  32.92707960636655,
  32.56284170683685,
  31.79349905851862,
  32.33981382870943,
  32.561729522286996,
  31.99074018177803],
 [33.0861915130064,
  32.76849713201887,
  32.69208366190413,
  32.61058197627314,
  32.65196963248253,
  32.69307502283212,
  32.624176754584546,
  32.90382582164076,
  32.80652029031667,
  33.064750225198125,
  33.05116725294506,
  32.84840207769539,
  32.99127188061618,
  33.09690917642787,
  32.636338875962124],
 [31.10716717259266,
  30.69560023658215,
  32.412063660027954,
  30.49717381063385,
  32.55264184963218,
  31.934247287800318,
  30.895435939978167,
  31.375849255750452,
  30.802047433409328,
  32.371966037017984,
  32.04460817936013,
  30.532328325448894,
  32.01662247114662,
  31.376400354904472,
  32.5442923600644],
 [29.528299009033482,
  28.92272825386287,
  28.919048007831535,
  29.78586145793733,
  29.554718138576128,
  29.75009021122492,
  29.683725556932426,
  30.12371807758751,
  30.1200468529393,
  29.597812264948036,
  29.94837280892901,
  29.64425083222522,
  30.30811572572143,
  29.356193295253465,
  29.000300906728835],
 [28.387869119708423,
  28.422292838930822,
  28.62619253259071,
  28.696098774015358,
  28.388148566342284,
  28.53142783317584,
  28.498612611905763,
  28.34880398201328,
  28.69099664269629,
  28.313029994110252,
  28.558793115835762,
  28.624186555488382,
  28.337178677454293,
  28.699991380492644,
  28.60077002167276],
 [27.944837119188612,
  27.94033389584813,
  27.727600050744666,
  27.630440745086528,
  27.765248369340043,
  27.5643256633079,
  28.030525764462755,
  27.88864719537074,
  27.835813981594693,
  28.01969685122807,
  27.5528434528653,
  27.75012319033782,
  27.859511127367725,
  27.682162737694348,
  27.94212273174681],
 [27.31100390559892,
  27.31359283640507,
  27.290767825039108,
  27.168995596234183,
  27.080385669753213,
  27.392648954166503,
  27.109203077448484,
  27.3438626753728,
  26.817106383056785,
  27.09334506070012,
  26.861422159339345,
  27.028665758302395,
  27.29188681371928,
  27.313956883716653,
  26.99295656683259],
 [26.30126631407759,
  26.761990954512985,
  26.439644234856566,
  26.614420556345596,
  26.626983682871714,
  26.395623925822584,
  26.311176384331684,
  26.40941239124002,
  26.38226192401132,
  26.513795518188463,
  26.555026120609966,
  26.5475024045631,
  26.621344665180814,
  26.330818470576677,
  26.687832382189388],
 [25.685746654381035,
  25.173121599247303,
  25.948276499987447,
  25.104456040947312,
  26.118348640245166,
  25.40943026607341,
  25.464586347807888,
  25.086245630574236,
  26.1128686171456,
  25.03537662810417,
  25.92618692847254,
  26.085921172456715,
  26.228073733658327,
  24.927674248934878,
  25.746930147032884],
 [24.28305060921107,
  24.443975530943966,
  24.47444054830637,
  24.21276116952731,
  24.21140074531302,
  24.851777975826568,
  24.548781464198832,
  24.56840584597161,
  24.705884410105607,
  24.431296980041875,
  24.608577851358472,
  24.510492116426686,
  24.778540097824745,
  24.420843312976427,
  24.5007068523679],
 [23.77392887255869,
  24.17731139902878,
  23.971981241978035,
  23.74531666245162,
  23.7367039802795,
  23.931867501970583,
  24.163014905844975,
  24.120555204033906,
  24.12630566178213,
  23.86740556686149,
  23.85430273173532,
  23.779775015657606,
  24.06837743131902,
  23.77411998386568,
  23.904434623987743],
 [23.154794453245138,
  23.335928451057114,
  23.146254960994995,
  23.204163217012248,
  23.14805776159059,
  23.22535779098576,
  23.696272533473312,
  23.108266486268846,
  23.605899334959208,
  23.509864891288288,
  23.620473837455513,
  23.144871818611286,
  23.2859798318377,
  23.67235541540453,
  23.49672942626468],
 [23.007594127989066,
  22.76775868217163,
  22.95002463060086,
  23.023752980948696,
  23.006814705040792,
  22.698242943024596,
  22.979725790126967,
  22.841683610140592,
  22.73038035307649,
  22.686351713115968,
  22.64234728733513,
  23.009021539793835,
  23.00751827281604,
  22.801252187902303,
  23.097150060781996],
 [22.112787115102154,
  22.55936397357663,
  22.020927019154485,
  22.277838447634895,
  22.428744235553626,
  22.45209070331278,
  22.068986639405942,
  22.234057262751563,
  22.44809793913003,
  22.270499182186597,
  22.44541260705777,
  22.144047865060937,
  22.5358379110532,
  22.565412821231916,
  22.146892173744313]]

In [90]:
pHA_list

[[7.818670991515116,
  7.733692760242836,
  7.818442715357965,
  7.760057974471307,
  7.803024148512008,
  7.78039593162075,
  7.787964496539523,
  7.743336361046309,
  7.74873108296885,
  7.7547501717383795,
  7.759525278246768,
  7.752960301590294,
  7.77088244405124,
  7.759082825606604,
  7.763946988879247],
 [7.8378497379137775,
  7.895135785582795,
  7.849716246323789,
  7.864562506750583,
  7.915522474265804,
  7.8778705842089645,
  7.941976426937999,
  7.903908085078946,
  7.832495981031882,
  7.936830771026462,
  7.8905438183226,
  7.8451358082614115,
  7.931996443863841,
  7.850850218773281,
  7.825201707635054],
 [8.111086640254504,
  8.105480515101814,
  8.12747205035217,
  7.965806554839446,
  8.11527005079688,
  7.978750116096995,
  8.033387996544413,
  8.137773849503311,
  7.978886336815607,
  8.109644768192878,
  8.102585716651214,
  7.961105280417475,
  8.044932839417536,
  8.00072278837316,
  8.162816264168494],
 [8.200658610426418,
  8.195952952971695,
  8.188055354314399,
  8.187837446893747,
  8.21254165460321,
  8.182176635913217,
  8.180755510733782,
  8.199430867949898,
  8.245240035201938,
  8.238619138667032,
  8.199326885987842,
  8.203117300272483,
  8.257865728236526,
  8.192732816766554,
  8.199414592182144],
 [8.457699519815762,
  8.46013389184663,
  8.297567960370065,
  8.289548525822235,
  8.460990801758614,
  8.339322040946046,
  8.465974619678326,
  8.277758907177185,
  8.345597457453607,
  8.345199127778441,
  8.469240958051165,
  8.416899582617518,
  8.308493332796205,
  8.336032800527617,
  8.411864803805562],
 [8.132806286932896,
  8.484385855701259,
  8.36907558844212,
  8.424153658611091,
  8.057237910142051,
  8.139392210850176,
  8.26933955067752,
  8.305386411267571,
  8.43121388223911,
  8.22049265426456,
  8.133633713969484,
  8.02688980914391,
  8.190212918126257,
  8.400620780195366,
  8.305781536837163],
 [7.946017339643835,
  7.382025801150442,
  7.368902921406172,
  7.886330089853865,
  7.853394528457259,
  7.39233901931038,
  7.7708004025898125,
  7.671868550220016,
  7.988315122643278,
  7.648176266317108,
  7.9460601091999585,
  7.698131778685276,
  7.644324704892407,
  7.958121760947366,
  7.6042020248132305],
 [7.0088091295812545,
  7.237870003028107,
  7.207298360748676,
  7.031811205717384,
  7.0426701550664745,
  7.2028036895722085,
  7.133918104688963,
  6.858309857144129,
  7.199996812577087,
  7.131903994749571,
  7.045220684632382,
  6.8930421605277274,
  7.027008013528187,
  6.933942676656484,
  6.903970978732747],
 [6.598183211362817,
  6.254940908695386,
  6.31703094291564,
  6.519856526793147,
  6.268999922117856,
  6.7040926610532425,
  6.267903483954354,
  6.264359667189714,
  6.357433441144228,
  6.462175090188416,
  6.570286995016509,
  6.769197887996924,
  6.657602423352979,
  6.397755126799936,
  6.224837541692634],
 [6.258591132171796,
  6.256553730734013,
  6.2808267803616165,
  6.268943196566487,
  6.276268677452465,
  6.235289158910455,
  6.26287285642502,
  6.276140472777276,
  6.288904911306094,
  6.289480809110398,
  6.290257390334913,
  6.276264990121983,
  6.264095480046044,
  6.240996574765218,
  6.264402373486942],
 [6.338571474521504,
  6.377684414092596,
  6.382599917910147,
  6.333132422653398,
  6.36123972586594,
  6.380052127123203,
  6.302230475572548,
  6.301962795038327,
  6.321855048626075,
  6.397423561036302,
  6.3064063398529795,
  6.326176199736983,
  6.3577521313555465,
  6.318544359505184,
  6.40895147664426],
 [6.480284359568712,
  6.422215631977025,
  6.443782524206008,
  6.441768536705911,
  6.51058531250561,
  6.515989024389088,
  6.415491040720719,
  6.411407673476009,
  6.480320548937473,
  6.415640482141898,
  6.464375313496313,
  6.45048826932442,
  6.553677267838409,
  6.523050232514867,
  6.456853834641319],
 [6.602609833206321,
  6.826396576933713,
  6.648953362753657,
  6.96924007498968,
  6.76453136093542,
  6.6632152366098,
  6.947275899648906,
  6.972145911568969,
  6.979738469120658,
  6.720908795225625,
  6.594011797449274,
  6.910176882956727,
  6.882286273617658,
  6.849278152767362,
  6.903076646907344],
 [7.0546788435074514,
  7.025635968713119,
  7.077542187075226,
  6.986983800739301,
  7.058861664597067,
  7.056674897337788,
  7.011007474439937,
  6.994042246647947,
  7.077796829654316,
  7.056667523738706,
  7.109567430548048,
  7.012529279295941,
  7.064590068227449,
  7.045910350878442,
  7.0707949090211475],
 [7.21153000669591,
  7.228712052269707,
  7.174050464074603,
  7.169199316198645,
  7.200379102109754,
  7.183470123827984,
  7.156302542817781,
  7.21785227828077,
  7.156468743989932,
  7.130070331987175,
  7.165503445659258,
  7.173291070765982,
  7.21873701435647,
  7.180118211364908,
  7.144698377226779],
 [7.2029533728854025,
  7.188855043632635,
  7.1784778589542535,
  7.163008360978253,
  7.190466757257326,
  7.222837643471926,
  7.173785386449284,
  7.207026651171528,
  7.197887378251183,
  7.171265148611488,
  7.210891673228798,
  7.168404166107742,
  7.202548516532356,
  7.157395230462447,
  7.201070776806237],
 [7.1271736175811204,
  7.137216303920336,
  7.128507032085112,
  7.143386546887013,
  7.146720525095634,
  7.125566283883026,
  7.134400516342854,
  7.127195519569093,
  7.122181240273938,
  7.130882309127882,
  7.141446152406878,
  7.120055382391133,
  7.139968432423853,
  7.1300905901026805,
  7.133950947925903],
 [7.234229644830871,
  7.159545328840351,
  7.159975686400599,
  7.184428273679447,
  7.150447996602514,
  7.158131504213733,
  7.2758240313173435,
  7.211053254600011,
  7.161756904550242,
  7.230072608703894,
  7.249997539362316,
  7.179526629349927,
  7.237454632333838,
  7.1326162368358315,
  7.28673107965323],
 [7.426328170647273,
  7.365634506051392,
  7.304784266146227,
  7.358858248840037,
  7.365484565060064,
  7.356629440633928,
  7.31113641312236,
  7.419811411460067,
  7.424066518398576,
  7.415732789207354,
  7.397076338231613,
  7.4042250387508854,
  7.326783718283593,
  7.320032982216013,
  7.2959554801998765],
 [7.45190275448154,
  7.481830202275621,
  7.502369777500731,
  7.482304440403363,
  7.473865118520738,
  7.465781107748681,
  7.480972168922384,
  7.47925891358901,
  7.509610923147034,
  7.45876761041334,
  7.4975162389063765,
  7.453158163918095,
  7.5031320903623415,
  7.474317143926761,
  7.472395617231489],
 [7.511734242634503,
  7.553512112781728,
  7.544785047764996,
  7.545604575624089,
  7.529128570525442,
  7.5316755527769805,
  7.563029989014603,
  7.5583361482010725,
  7.533601816511252,
  7.581163813539238,
  7.567135498783607,
  7.512128879284399,
  7.5307034493798275,
  7.514535234539057,
  7.5195850844890595],
 [7.592367724095357,
  7.593255262636858,
  7.596911602461773,
  7.594791910007649,
  7.594674107730375,
  7.596568078268496,
  7.591407370726409,
  7.59180992322131,
  7.592192234791303,
  7.59032394794117,
  7.594869729831956,
  7.599350791504193,
  7.598928505915789,
  7.594356779692017,
  7.595747590723087],
 [7.667170038887313,
  7.630013726236492,
  7.681637626805553,
  7.658817906624744,
  7.632485436145309,
  7.618303303049041,
  7.664557015424724,
  7.633206754794845,
  7.644251130097204,
  7.687469982163874,
  7.606931156004381,
  7.629708445955643,
  7.6157403343640615,
  7.617342697046425,
  7.6574247231024986]]

In [91]:
test = temp.copy()

In [92]:
test

    TempA  TempB  TempC  TempD
0    21.5   21.2   21.3   21.4
1    21.0   20.8   20.5   20.7
2    20.5   20.2   20.3   20.2
3    20.3   20.0   20.1   19.9
4    21.0   20.6   21.1   20.9
5    21.8   22.0   21.7   21.5
6    24.9   24.6   24.8   24.7
7    26.8   26.9   27.0   26.9
8    29.1   28.9   29.3   29.7
9    31.7   31.5   31.2   31.3
10   33.1   32.7   32.9   32.8
11   32.6   32.2   32.3   32.1
12   30.4   30.5   30.3   30.1
13   28.7   28.9   28.4   28.1
14   28.3   28.1   27.9   27.9
15   27.5   27.8   27.2   27.1
16   26.8   27.0   26.4   26.2
17   26.3   26.5   26.2   26.1
18   24.9   24.8   25.3   25.0
19   24.2   24.3   24.7   24.5
20   23.7   23.2   23.5   23.1
21   23.1   22.8   23.0   22.6
22   22.6   22.1   22.4   22.0
23   22.0   21.7   21.9   21.8

In [93]:
tempA_list[0]

[21.20619169199319,
 21.210902468590238,
 21.257416475726465,
 21.093704869879527,
 21.20844155436343,
 21.448270144069557,
 21.228976703133487,
 21.015191755577792,
 21.2503309740264,
 21.331753928970205,
 21.070343034615306,
 21.47695308574595,
 21.46012376385791,
 21.172848197043635,
 21.346330516729868]

In [94]:
tempA_mat[0]

array([21.20619169, 21.21090247, 21.25741648, 21.09370487, 21.20844155,
       21.44827014, 21.2289767 , 21.01519176, 21.25033097, 21.33175393,
       21.07034303, 21.47695309, 21.46012376, 21.1728482 , 21.34633052])

In [102]:
temp = pd.DataFrame(tempA_list)

In [103]:
temp.T

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,21.206192,20.893399,20.359393,20.924390,21.249288,23.514003,26.054055,28.566661,29.555437,32.149301,...,28.387869,27.944837,27.311004,26.301266,25.685747,24.283051,23.773929,23.154794,23.007594,22.112787
1,21.210902,20.553094,20.472739,20.953833,21.527635,22.545370,26.278721,28.033207,31.003889,32.035874,...,28.422293,27.940334,27.313593,26.761991,25.173122,24.443976,24.177311,23.335928,22.767759,22.559364
2,21.257416,20.840133,20.432175,20.776236,21.187028,21.860403,25.426567,28.817831,29.895411,33.060348,...,28.626193,27.727600,27.290768,26.439644,25.948276,24.474441,23.971981,23.146255,22.950025,22.020927
3,21.093705,20.947528,20.377562,20.558153,21.524502,24.439887,26.106223,29.077458,31.354591,32.019159,...,28.696099,27.630441,27.168996,26.614421,25.104456,24.212761,23.745317,23.204163,23.023753,22.277838
4,21.208442,20.728379,20.380355,20.710097,21.240873,23.301225,26.749052,28.456047,30.650005,31.930606,...,28.388149,27.765248,27.080386,26.626984,26.118349,24.211401,23.736704,23.148058,23.006815,22.428744
5,21.448270,20.766414,20.458630,20.404766,21.338511,22.614765,26.746923,27.258264,29.291333,32.146403,...,28.531428,27.564326,27.392649,26.395624,25.409430,24.851778,23.931868,23.225358,22.698243,22.452091
6,21.228977,20.706632,20.407705,20.383632,21.092605,24.672310,26.647263,28.173021,30.546058,32.469932,...,28.498613,28.030526,27.109203,26.311176,25.464586,24.548781,24.163015,23.696273,22.979726,22.068987
7,21.015192,20.832313,20.476708,20.460869,21.033699,23.961031,25.933045,27.096306,31.645341,31.799907,...,28.348804,27.888647,27.343863,26.409412,25.086246,24.568406,24.120555,23.108266,22.841684,22.234057
8,21.250331,20.782690,20.350423,20.659353,21.668217,23.824478,25.148339,28.384737,30.210802,32.221618,...,28.690997,27.835814,26.817106,26.382262,26.112869,24.705884,24.126306,23.605899,22.730380,22.448098
9,21.331754,20.946935,20.344439,20.964541,21.123518,23.110478,25.399630,27.317081,30.260468,32.927080,...,28.313030,28.019697,27.093345,26.513796,25.035377,24.431297,23.867406,23.509865,22.686352,22.270499
10,21.070343,20.652473,20.393503,20.362513,21.291384,22.516593,25.231905,29.044412,31.495661,32.562842,...,28.558793,27.552843,26.861422,26.555026,25.926187,24.608578,23.854303,23.620474,22.642347,22.445413
11,21.476953,20.717388,20.389054,20.795170,21.684438,23.493657,26.101369,28.763197,30.289629,31.793499,...,28.624187,27.750123,27.028666,26.547502,26.085921,24.510492,23.779775,23.144872,23.009022,22.144048
12,21.460124,20.812310,20.300157,20.927156,21.738416,22.763259,25.856170,27.397373,29.598055,32.339814,...,28.337179,27.859511,27.291887,26.621345,26.228074,24.778540,24.068377,23.285980,23.007518,22.535838
13,21.172848,20.667924,20.341508,20.321112,21.600599,22.533325,26.404339,28.275259,31.247040,32.561730,...,28.699991,27.682163,27.313957,26.330818,24.927674,24.420843,23.774120,23.672355,22.801252,22.565413
14,21.346331,20.983164,20.397473,20.319418,21.473564,23.415676,26.652426,28.138991,31.185085,31.990740,...,28.600770,27.942123,26.992957,26.687832,25.746930,24.500707,23.904435,23.496729,23.097150,22.146892

In [104]:
tempA = pd.DataFrame(tempA_list)
tempB = pd.DataFrame(tempB_list)
tempC = pd.DataFrame(tempC_list)
tempD = pd.DataFrame(tempD_list)

pHA = pd.DataFrame(pHA_list)
pHB = pd.DataFrame(pHB_list)
pHC = pd.DataFrame(pHC_list)
pHD = pd.DataFrame(pHD_list)

DOA = pd.DataFrame(DOA_list)
DOB = pd.DataFrame(DOB_list)
DOC = pd.DataFrame(DOC_list)
DOD = pd.DataFrame(DOD_list)

BODA = pd.DataFrame(BODA_list)
BODB = pd.DataFrame(BODB_list)
BODC = pd.DataFrame(BODC_list)
BODD = pd.DataFrame(BODD_list)

ECA = pd.DataFrame(ECA_list)
ECB = pd.DataFrame(ECB_list)
ECC = pd.DataFrame(ECC_list)
ECD = pd.DataFrame(ECD_list)

TNA = pd.DataFrame(TNA_list)
TNB = pd.DataFrame(TNB_list)
TNC = pd.DataFrame(TNC_list)
TND = pd.DataFrame(TND_list)

In [105]:
tempA = tempA.T
tempB = tempB.T
tempC = tempC.T
tempD = tempD.T

pHA = pHA.T
pHB = pHB.T
pHC = pHC.T
pHD = pHD.T

ECA = ECA.T
ECB = ECB.T
ECC = ECC.T
ECD = ECD.T

DOA = DOA.T
DOB = DOB.T
DOC = DOC.T
DOD = DOD.T

BODA = BODA.T
BODB = BODB.T
BODC = BODC.T
BODD = BODD.T

TNA = TNA.T
TNB = TNB.T
TNC = TNC.T
TND = TND.T

In [106]:
tempA.to_csv("tempA.csv")
tempB.to_csv("tempB.csv")
tempC.to_csv("tempC.csv")
tempD.to_csv("tempD.csv")


pHA.to_csv("pHA.csv")
pHB.to_csv("pHB.csv")
pHC.to_csv("pHC.csv")
pHD.to_csv("pHD.csv")   

ECA.to_csv("ECA.csv")
ECB.to_csv("ECB.csv")
ECC.to_csv("ECC.csv")
ECD.to_csv("ECD.csv")   

DOA.to_csv("DOA.csv")
DOB.to_csv("DOB.csv")
DOC.to_csv("DOC.csv")
DOD.to_csv("DOD.csv")   

BODA.to_csv("BODA.csv")
BODB.to_csv("BODB.csv")
BODC.to_csv("BODC.csv")
BODD.to_csv("BODD.csv")   

TNA.to_csv("TNA.csv")
TNB.to_csv("TNB.csv")
TNC.to_csv("TNC.csv")
TND.to_csv("TND.csv")

In [107]:
tempA

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,21.206192,20.893399,20.359393,20.924390,21.249288,23.514003,26.054055,28.566661,29.555437,32.149301,...,28.387869,27.944837,27.311004,26.301266,25.685747,24.283051,23.773929,23.154794,23.007594,22.112787
1,21.210902,20.553094,20.472739,20.953833,21.527635,22.545370,26.278721,28.033207,31.003889,32.035874,...,28.422293,27.940334,27.313593,26.761991,25.173122,24.443976,24.177311,23.335928,22.767759,22.559364
2,21.257416,20.840133,20.432175,20.776236,21.187028,21.860403,25.426567,28.817831,29.895411,33.060348,...,28.626193,27.727600,27.290768,26.439644,25.948276,24.474441,23.971981,23.146255,22.950025,22.020927
3,21.093705,20.947528,20.377562,20.558153,21.524502,24.439887,26.106223,29.077458,31.354591,32.019159,...,28.696099,27.630441,27.168996,26.614421,25.104456,24.212761,23.745317,23.204163,23.023753,22.277838
4,21.208442,20.728379,20.380355,20.710097,21.240873,23.301225,26.749052,28.456047,30.650005,31.930606,...,28.388149,27.765248,27.080386,26.626984,26.118349,24.211401,23.736704,23.148058,23.006815,22.428744
5,21.448270,20.766414,20.458630,20.404766,21.338511,22.614765,26.746923,27.258264,29.291333,32.146403,...,28.531428,27.564326,27.392649,26.395624,25.409430,24.851778,23.931868,23.225358,22.698243,22.452091
6,21.228977,20.706632,20.407705,20.383632,21.092605,24.672310,26.647263,28.173021,30.546058,32.469932,...,28.498613,28.030526,27.109203,26.311176,25.464586,24.548781,24.163015,23.696273,22.979726,22.068987
7,21.015192,20.832313,20.476708,20.460869,21.033699,23.961031,25.933045,27.096306,31.645341,31.799907,...,28.348804,27.888647,27.343863,26.409412,25.086246,24.568406,24.120555,23.108266,22.841684,22.234057
8,21.250331,20.782690,20.350423,20.659353,21.668217,23.824478,25.148339,28.384737,30.210802,32.221618,...,28.690997,27.835814,26.817106,26.382262,26.112869,24.705884,24.126306,23.605899,22.730380,22.448098
9,21.331754,20.946935,20.344439,20.964541,21.123518,23.110478,25.399630,27.317081,30.260468,32.927080,...,28.313030,28.019697,27.093345,26.513796,25.035377,24.431297,23.867406,23.509865,22.686352,22.270499
10,21.070343,20.652473,20.393503,20.362513,21.291384,22.516593,25.231905,29.044412,31.495661,32.562842,...,28.558793,27.552843,26.861422,26.555026,25.926187,24.608578,23.854303,23.620474,22.642347,22.445413
11,21.476953,20.717388,20.389054,20.795170,21.684438,23.493657,26.101369,28.763197,30.289629,31.793499,...,28.624187,27.750123,27.028666,26.547502,26.085921,24.510492,23.779775,23.144872,23.009022,22.144048
12,21.460124,20.812310,20.300157,20.927156,21.738416,22.763259,25.856170,27.397373,29.598055,32.339814,...,28.337179,27.859511,27.291887,26.621345,26.228074,24.778540,24.068377,23.285980,23.007518,22.535838
13,21.172848,20.667924,20.341508,20.321112,21.600599,22.533325,26.404339,28.275259,31.247040,32.561730,...,28.699991,27.682163,27.313957,26.330818,24.927674,24.420843,23.774120,23.672355,22.801252,22.565413
14,21.346331,20.983164,20.397473,20.319418,21.473564,23.415676,26.652426,28.138991,31.185085,31.990740,...,28.600770,27.942123,26.992957,26.687832,25.746930,24.500707,23.904435,23.496729,23.097150,22.146892

In [4]:
import datetime
import pandas as pd
 
# initializing date
test_date = datetime.datetime.strptime("16-12-2021", "%d-%m-%Y")
 
# initializing K
K = 14
 
date_generated = pd.date_range(test_date, periods=K)
date_generated

DatetimeIndex(['2021-12-16', '2021-12-17', '2021-12-18', '2021-12-19',
               '2021-12-20', '2021-12-21', '2021-12-22', '2021-12-23',
               '2021-12-24', '2021-12-25', '2021-12-26', '2021-12-27',
               '2021-12-28', '2021-12-29'],
              dtype='datetime64[ns]', freq='D')

In [109]:
test_date = datetime.datetime.strptime("16-12-2021", "%d-%m-%Y")
day0 = pd.date_range(test_date, periods=14)

test_date = datetime.datetime.strptime("31-12-2021", "%d-%m-%Y")
day1 = pd.date_range(test_date, periods=15)

test_date = datetime.datetime.strptime("16-1-2022", "%d-%m-%Y")
day2 = pd.date_range(test_date, periods=14)

test_date = datetime.datetime.strptime("31-1-2022", "%d-%m-%Y")
day3 = pd.date_range(test_date, periods=15)

test_date = datetime.datetime.strptime("16-2-2022", "%d-%m-%Y")
day4 = pd.date_range(test_date, periods=12)

test_date = datetime.datetime.strptime("1-3-2022", "%d-%m-%Y")
day5 = pd.date_range(test_date, periods=14)

test_date = datetime.datetime.strptime("16-3-2022", "%d-%m-%Y")
day6 = pd.date_range(test_date, periods=14)

test_date = datetime.datetime.strptime("31-3-2022", "%d-%m-%Y")
day7 = pd.date_range(test_date, periods=15)

test_date = datetime.datetime.strptime("16-4-2022", "%d-%m-%Y")
day8 = pd.date_range(test_date, periods=14)

test_date = datetime.datetime.strptime("1-5-2022", "%d-%m-%Y")
day9 = pd.date_range(test_date, periods=14)

test_date = datetime.datetime.strptime("16-5-2022", "%d-%m-%Y")
day10 = pd.date_range(test_date, periods=14)

test_date = datetime.datetime.strptime("31-5-2022", "%d-%m-%Y")
day11 = pd.date_range(test_date, periods=15)

test_date = datetime.datetime.strptime("16-6-2022", "%d-%m-%Y")
day12 = pd.date_range(test_date, periods=14)

test_date = datetime.datetime.strptime("1-7-2022", "%d-%m-%Y")
day13 = pd.date_range(test_date, periods=14)

test_date = datetime.datetime.strptime("15-7-2022", "%d-%m-%Y")
day14 = pd.date_range(test_date, periods=14)

test_date = datetime.datetime.strptime("31-7-2022", "%d-%m-%Y")
day15 = pd.date_range(test_date, periods=15)

test_date = datetime.datetime.strptime("16-8-2022", "%d-%m-%Y")
day16 = pd.date_range(test_date, periods=14)

test_date = datetime.datetime.strptime("31-8-2022", "%d-%m-%Y")
day17 = pd.date_range(test_date, periods=15)

test_date = datetime.datetime.strptime("16-9-2022", "%d-%m-%Y")
day18 = pd.date_range(test_date, periods=14)

test_date = datetime.datetime.strptime("1-10-2022", "%d-%m-%Y")
day19 = pd.date_range(test_date, periods=14)

test_date = datetime.datetime.strptime("16-10-2022", "%d-%m-%Y")
day20 = pd.date_range(test_date, periods=14)

test_date = datetime.datetime.strptime("31-10-2022", "%d-%m-%Y")
day21 = pd.date_range(test_date, periods=15)

test_date = datetime.datetime.strptime("16-11-2022", "%d-%m-%Y")
day22 = pd.date_range(test_date, periods=14)

In [110]:
day1

DatetimeIndex(['2021-12-31', '2022-01-01', '2022-01-02', '2022-01-03',
               '2022-01-04', '2022-01-05', '2022-01-06', '2022-01-07',
               '2022-01-08', '2022-01-09', '2022-01-10', '2022-01-11',
               '2022-01-12', '2022-01-13', '2022-01-14'],
              dtype='datetime64[ns]', freq='D')

In [111]:
cols = ["day0",
        "day1",
        "day2",
        "day3",
        "day4",
        "day5",
        "day6",
        "day7",
        "day8",
        "day9",
        "day10",
        "day11",
        "day12",
        "day13",
        "day14",
        "day15",
        "day16",
        "day17",
        "day18",
        "day19",
        "day20",
        "day21",
        "day22"]

In [112]:
temp = [tempA,tempB,tempC,tempD]
pH = [pHA,pHB,pHC,pHD]
EC = [ECA,ECB,ECC,ECD]
DO = [DOA,DOB,DOC,DOD]
BOD = [BODA,BODB,BODC,BODD]
TN = [TNA,TNB,TNC,TND]

In [113]:
for df in temp:
    df.columns = cols

for df in pH:
    df.columns = cols

for df in EC:
    df.columns = cols

for df in DO:
    df.columns = cols

for df in BOD:
    df.columns = cols

for df in TN:
    df.columns = cols

In [114]:
tempA

,day0,day1,day2,day3,day4,day5,day6,day7,day8,day9,...,day13,day14,day15,day16,day17,day18,day19,day20,day21,day22
0,21.206192,20.893399,20.359393,20.924390,21.249288,23.514003,26.054055,28.566661,29.555437,32.149301,...,28.387869,27.944837,27.311004,26.301266,25.685747,24.283051,23.773929,23.154794,23.007594,22.112787
1,21.210902,20.553094,20.472739,20.953833,21.527635,22.545370,26.278721,28.033207,31.003889,32.035874,...,28.422293,27.940334,27.313593,26.761991,25.173122,24.443976,24.177311,23.335928,22.767759,22.559364
2,21.257416,20.840133,20.432175,20.776236,21.187028,21.860403,25.426567,28.817831,29.895411,33.060348,...,28.626193,27.727600,27.290768,26.439644,25.948276,24.474441,23.971981,23.146255,22.950025,22.020927
3,21.093705,20.947528,20.377562,20.558153,21.524502,24.439887,26.106223,29.077458,31.354591,32.019159,...,28.696099,27.630441,27.168996,26.614421,25.104456,24.212761,23.745317,23.204163,23.023753,22.277838
4,21.208442,20.728379,20.380355,20.710097,21.240873,23.301225,26.749052,28.456047,30.650005,31.930606,...,28.388149,27.765248,27.080386,26.626984,26.118349,24.211401,23.736704,23.148058,23.006815,22.428744
5,21.448270,20.766414,20.458630,20.404766,21.338511,22.614765,26.746923,27.258264,29.291333,32.146403,...,28.531428,27.564326,27.392649,26.395624,25.409430,24.851778,23.931868,23.225358,22.698243,22.452091
6,21.228977,20.706632,20.407705,20.383632,21.092605,24.672310,26.647263,28.173021,30.546058,32.469932,...,28.498613,28.030526,27.109203,26.311176,25.464586,24.548781,24.163015,23.696273,22.979726,22.068987
7,21.015192,20.832313,20.476708,20.460869,21.033699,23.961031,25.933045,27.096306,31.645341,31.799907,...,28.348804,27.888647,27.343863,26.409412,25.086246,24.568406,24.120555,23.108266,22.841684,22.234057
8,21.250331,20.782690,20.350423,20.659353,21.668217,23.824478,25.148339,28.384737,30.210802,32.221618,...,28.690997,27.835814,26.817106,26.382262,26.112869,24.705884,24.126306,23.605899,22.730380,22.448098
9,21.331754,20.946935,20.344439,20.964541,21.123518,23.110478,25.399630,27.317081,30.260468,32.927080,...,28.313030,28.019697,27.093345,26.513796,25.035377,24.431297,23.867406,23.509865,22.686352,22.270499
10,21.070343,20.652473,20.393503,20.362513,21.291384,22.516593,25.231905,29.044412,31.495661,32.562842,...,28.558793,27.552843,26.861422,26.555026,25.926187,24.608578,23.854303,23.620474,22.642347,22.445413
11,21.476953,20.717388,20.389054,20.795170,21.684438,23.493657,26.101369,28.763197,30.289629,31.793499,...,28.624187,27.750123,27.028666,26.547502,26.085921,24.510492,23.779775,23.144872,23.009022,22.144048
12,21.460124,20.812310,20.300157,20.927156,21.738416,22.763259,25.856170,27.397373,29.598055,32.339814,...,28.337179,27.859511,27.291887,26.621345,26.228074,24.778540,24.068377,23.285980,23.007518,22.535838
13,21.172848,20.667924,20.341508,20.321112,21.600599,22.533325,26.404339,28.275259,31.247040,32.561730,...,28.699991,27.682163,27.313957,26.330818,24.927674,24.420843,23.774120,23.672355,22.801252,22.565413
14,21.346331,20.983164,20.397473,20.319418,21.473564,23.415676,26.652426,28.138991,31.185085,31.990740,...,28.600770,27.942123,26.992957,26.687832,25.746930,24.500707,23.904435,23.496729,23.097150,22.146892

In [153]:
range0 = pd.DataFrame(data={
    
    "TempA": tempA["day0"],
    "TempB": tempB["day0"],
    "TempC": tempC["day0"],
    "TempD": tempD["day0"],
    
    "pHA": pHA["day0"],
    "pHB": pHB["day0"],
    "pHC": pHC["day0"],
    "pHD": pHD["day0"],
    
    "ECA": ECA["day0"],
    "ECB": ECB["day0"],
    "ECC": ECC["day0"],
    "ECD": ECD["day0"],
    
    "DOA": DOA["day0"],
    "DOB": DOB["day0"],
    "DOC": DOC["day0"],
    "DOD": DOD["day0"],
    
    "BODA": BODA["day0"],
    "BODB": BODB["day0"],
    "BODC": BODC["day0"],
    "BODD": BODD["day0"],
    
    "TNA": TNA["day0"],
    "TNB": TNB["day0"],
    "TNC": TNC["day0"],
    "TND": TND["day0"],

})

range1 = pd.DataFrame(data={
    
    "TempA": tempA["day1"],
    "TempB": tempB["day1"],
    "TempC": tempC["day1"],
    "TempD": tempD["day1"],
    
    "pHA": pHA["day1"],
    "pHB": pHB["day1"],
    "pHC": pHC["day1"],
    "pHD": pHD["day1"],
    
    "ECA": ECA["day1"],
    "ECB": ECB["day1"],
    "ECC": ECC["day1"],
    "ECD": ECD["day1"],
    
    "DOA": DOA["day1"],
    "DOB": DOB["day1"],
    "DOC": DOC["day1"],
    "DOD": DOD["day1"],
    
    "BODA": BODA["day1"],
    "BODB": BODB["day1"],
    "BODC": BODC["day1"],
    "BODD": BODD["day1"],
    
    "TNA": TNA["day1"],
    "TNB": TNB["day1"],
    "TNC": TNC["day1"],
    "TND": TND["day1"],

})

range2 = pd.DataFrame(data={
    
    "TempA": tempA["day2"],
    "TempB": tempB["day2"],
    "TempC": tempC["day2"],
    "TempD": tempD["day2"],
    
    "pHA": pHA["day2"],
    "pHB": pHB["day2"],
    "pHC": pHC["day2"],
    "pHD": pHD["day2"],
    
    "ECA": ECA["day2"],
    "ECB": ECB["day2"],
    "ECC": ECC["day2"],
    "ECD": ECD["day2"],
    
    "DOA": DOA["day2"],
    "DOB": DOB["day2"],
    "DOC": DOC["day2"],
    "DOD": DOD["day2"],
    
    "BODA": BODA["day2"],
    "BODB": BODB["day2"],
    "BODC": BODC["day2"],
    "BODD": BODD["day2"],
    
    "TNA": TNA["day2"],
    "TNB": TNB["day2"],
    "TNC": TNC["day2"],
    "TND": TND["day2"],

})


range3 = pd.DataFrame(data={
    
    "TempA": tempA["day3"],
    "TempB": tempB["day3"],
    "TempC": tempC["day3"],
    "TempD": tempD["day3"],
    
    "pHA": pHA["day3"],
    "pHB": pHB["day3"],
    "pHC": pHC["day3"],
    "pHD": pHD["day3"],
    
    "ECA": ECA["day3"],
    "ECB": ECB["day3"],
    "ECC": ECC["day3"],
    "ECD": ECD["day3"],
    
    "DOA": DOA["day3"],
    "DOB": DOB["day3"],
    "DOC": DOC["day3"],
    "DOD": DOD["day3"],
    
    "BODA": BODA["day3"],
    "BODB": BODB["day3"],
    "BODC": BODC["day3"],
    "BODD": BODD["day3"],
    
    "TNA": TNA["day3"],
    "TNB": TNB["day3"],
    "TNC": TNC["day3"],
    "TND": TND["day3"],

})

range4 = pd.DataFrame(data={
    
    "TempA": tempA["day4"],
    "TempB": tempB["day4"],
    "TempC": tempC["day4"],
    "TempD": tempD["day4"],
    
    "pHA": pHA["day4"],
    "pHB": pHB["day4"],
    "pHC": pHC["day4"],
    "pHD": pHD["day4"],
    
    "ECA": ECA["day4"],
    "ECB": ECB["day4"],
    "ECC": ECC["day4"],
    "ECD": ECD["day4"],
    
    "DOA": DOA["day4"],
    "DOB": DOB["day4"],
    "DOC": DOC["day4"],
    "DOD": DOD["day4"],
    
    "BODA": BODA["day4"],
    "BODB": BODB["day4"],
    "BODC": BODC["day4"],
    "BODD": BODD["day4"],
    
    "TNA": TNA["day4"],
    "TNB": TNB["day4"],
    "TNC": TNC["day4"],
    "TND": TND["day4"],

})

range5 = pd.DataFrame(data={

    
    "TempA": tempA["day5"],
    "TempB": tempB["day5"],
    "TempC": tempC["day5"],
    "TempD": tempD["day5"],
    
    "pHA": pHA["day5"],
    "pHB": pHB["day5"],
    "pHC": pHC["day5"],
    "pHD": pHD["day5"],
    
    "ECA": ECA["day5"],
    "ECB": ECB["day5"],
    "ECC": ECC["day5"],
    "ECD": ECD["day5"],
    
    "DOA": DOA["day5"],
    "DOB": DOB["day5"],
    "DOC": DOC["day5"],
    "DOD": DOD["day5"],
    
    "BODA": BODA["day5"],
    "BODB": BODB["day5"],
    "BODC": BODC["day5"],
    "BODD": BODD["day5"],
    
    "TNA": TNA["day5"],
    "TNB": TNB["day5"],
    "TNC": TNC["day5"],
    "TND": TND["day5"],

})


range6 = pd.DataFrame(data={
    
    "TempA": tempA["day6"],
    "TempB": tempB["day6"],
    "TempC": tempC["day6"],
    "TempD": tempD["day6"],
    
    "pHA": pHA["day6"],
    "pHB": pHB["day6"],
    "pHC": pHC["day6"],
    "pHD": pHD["day6"],
    
    "ECA": ECA["day6"],
    "ECB": ECB["day6"],
    "ECC": ECC["day6"],
    "ECD": ECD["day6"],
    
    "DOA": DOA["day6"],
    "DOB": DOB["day6"],
    "DOC": DOC["day6"],
    "DOD": DOD["day6"],
    
    "BODA": BODA["day6"],
    "BODB": BODB["day6"],
    "BODC": BODC["day6"],
    "BODD": BODD["day6"],
    
    "TNA": TNA["day6"],
    "TNB": TNB["day6"],
    "TNC": TNC["day6"],
    "TND": TND["day6"],

})


range7 = pd.DataFrame(data={
    
    "TempA": tempA["day7"],
    "TempB": tempB["day7"],
    "TempC": tempC["day7"],
    "TempD": tempD["day7"],
    
    "pHA": pHA["day7"],
    "pHB": pHB["day7"],
    "pHC": pHC["day7"],
    "pHD": pHD["day7"],
    
    "ECA": ECA["day7"],
    "ECB": ECB["day7"],
    "ECC": ECC["day7"],
    "ECD": ECD["day7"],
    
    "DOA": DOA["day7"],
    "DOB": DOB["day7"],
    "DOC": DOC["day7"],
    "DOD": DOD["day7"],
    
    "BODA": BODA["day7"],
    "BODB": BODB["day7"],
    "BODC": BODC["day7"],
    "BODD": BODD["day7"],
    
    "TNA": TNA["day7"],
    "TNB": TNB["day7"],
    "TNC": TNC["day7"],
    "TND": TND["day7"],

})


range8 = pd.DataFrame(data={
    
    "TempA": tempA["day8"],
    "TempB": tempB["day8"],
    "TempC": tempC["day8"],
    "TempD": tempD["day8"],
    
    "pHA": pHA["day8"],
    "pHB": pHB["day8"],
    "pHC": pHC["day8"],
    "pHD": pHD["day8"],
    
    "ECA": ECA["day8"],
    "ECB": ECB["day8"],
    "ECC": ECC["day8"],
    "ECD": ECD["day8"],
    
    "DOA": DOA["day8"],
    "DOB": DOB["day8"],
    "DOC": DOC["day8"],
    "DOD": DOD["day8"],
    
    "BODA": BODA["day8"],
    "BODB": BODB["day8"],
    "BODC": BODC["day8"],
    "BODD": BODD["day8"],
    
    "TNA": TNA["day8"],
    "TNB": TNB["day8"],
    "TNC": TNC["day8"],
    "TND": TND["day8"],

})


range9 = pd.DataFrame(data={
    
    "TempA": tempA["day9"],
    "TempB": tempB["day9"],
    "TempC": tempC["day9"],
    "TempD": tempD["day9"],
    
    "pHA": pHA["day9"],
    "pHB": pHB["day9"],
    "pHC": pHC["day9"],
    "pHD": pHD["day9"],
    
    "ECA": ECA["day9"],
    "ECB": ECB["day9"],
    "ECC": ECC["day9"],
    "ECD": ECD["day9"],
    
    "DOA": DOA["day9"],
    "DOB": DOB["day9"],
    "DOC": DOC["day9"],
    "DOD": DOD["day9"],
    
    "BODA": BODA["day9"],
    "BODB": BODB["day9"],
    "BODC": BODC["day9"],
    "BODD": BODD["day9"],
    
    "TNA": TNA["day9"],
    "TNB": TNB["day9"],
    "TNC": TNC["day9"],
    "TND": TND["day9"],

})


range10 = pd.DataFrame(data={
    
    "TempA": tempA["day10"],
    "TempB": tempB["day10"],
    "TempC": tempC["day10"],
    "TempD": tempD["day10"],
    
    "pHA": pHA["day10"],
    "pHB": pHB["day10"],
    "pHC": pHC["day10"],
    "pHD": pHD["day10"],
    
    "ECA": ECA["day10"],
    "ECB": ECB["day10"],
    "ECC": ECC["day10"],
    "ECD": ECD["day10"],
    
    "DOA": DOA["day10"],
    "DOB": DOB["day10"],
    "DOC": DOC["day10"],
    "DOD": DOD["day10"],
    
    "BODA": BODA["day10"],
    "BODB": BODB["day10"],
    "BODC": BODC["day10"],
    "BODD": BODD["day10"],
    
    "TNA": TNA["day10"],
    "TNB": TNB["day10"],
    "TNC": TNC["day10"],
    "TND": TND["day10"],

})


range11 = pd.DataFrame(data={
    
    "TempA": tempA["day11"],
    "TempB": tempB["day11"],
    "TempC": tempC["day11"],
    "TempD": tempD["day11"],
    
    "pHA": pHA["day11"],
    "pHB": pHB["day11"],
    "pHC": pHC["day11"],
    "pHD": pHD["day11"],
    
    "ECA": ECA["day11"],
    "ECB": ECB["day11"],
    "ECC": ECC["day11"],
    "ECD": ECD["day11"],
    
    "DOA": DOA["day11"],
    "DOB": DOB["day11"],
    "DOC": DOC["day11"],
    "DOD": DOD["day11"],
    
    "BODA": BODA["day11"],
    "BODB": BODB["day11"],
    "BODC": BODC["day11"],
    "BODD": BODD["day11"],
    
    "TNA": TNA["day11"],
    "TNB": TNB["day11"],
    "TNC": TNC["day11"],
    "TND": TND["day11"],

})

range12 = pd.DataFrame(data={
    
    "TempA": tempA["day12"],
    "TempB": tempB["day12"],
    "TempC": tempC["day12"],
    "TempD": tempD["day12"],
    
    "pHA": pHA["day12"],
    "pHB": pHB["day12"],
    "pHC": pHC["day12"],
    "pHD": pHD["day12"],
    
    "ECA": ECA["day12"],
    "ECB": ECB["day12"],
    "ECC": ECC["day12"],
    "ECD": ECD["day12"],
    
    "DOA": DOA["day12"],
    "DOB": DOB["day12"],
    "DOC": DOC["day12"],
    "DOD": DOD["day12"],
    
    "BODA": BODA["day12"],
    "BODB": BODB["day12"],
    "BODC": BODC["day12"],
    "BODD": BODD["day12"],
    
    "TNA": TNA["day12"],
    "TNB": TNB["day12"],
    "TNC": TNC["day12"],
    "TND": TND["day12"],

})

range13 = pd.DataFrame(data={
    
    "TempA": tempA["day13"],
    "TempB": tempB["day13"],
    "TempC": tempC["day13"],
    "TempD": tempD["day13"],
    
    "pHA": pHA["day13"],
    "pHB": pHB["day13"],
    "pHC": pHC["day13"],
    "pHD": pHD["day13"],
    
    "ECA": ECA["day13"],
    "ECB": ECB["day13"],
    "ECC": ECC["day13"],
    "ECD": ECD["day13"],
    
    "DOA": DOA["day13"],
    "DOB": DOB["day13"],
    "DOC": DOC["day13"],
    "DOD": DOD["day13"],
    
    "BODA": BODA["day13"],
    "BODB": BODB["day13"],
    "BODC": BODC["day13"],
    "BODD": BODD["day13"],
    
    "TNA": TNA["day13"],
    "TNB": TNB["day13"],
    "TNC": TNC["day13"],
    "TND": TND["day13"],

})

range14 = pd.DataFrame(data={
    
    "TempA": tempA["day14"],
    "TempB": tempB["day14"],
    "TempC": tempC["day14"],
    "TempD": tempD["day14"],
    
    "pHA": pHA["day14"],
    "pHB": pHB["day14"],
    "pHC": pHC["day14"],
    "pHD": pHD["day14"],
    
    "ECA": ECA["day14"],
    "ECB": ECB["day14"],
    "ECC": ECC["day14"],
    "ECD": ECD["day14"],
    
    "DOA": DOA["day14"],
    "DOB": DOB["day14"],
    "DOC": DOC["day14"],
    "DOD": DOD["day14"],
    
    "BODA": BODA["day14"],
    "BODB": BODB["day14"],
    "BODC": BODC["day14"],
    "BODD": BODD["day14"],
    
    "TNA": TNA["day14"],
    "TNB": TNB["day14"],
    "TNC": TNC["day14"],
    "TND": TND["day14"],

})


range15 = pd.DataFrame(data={
    
    "TempA": tempA["day15"],
    "TempB": tempB["day15"],
    "TempC": tempC["day15"],
    "TempD": tempD["day15"],
    
    "pHA": pHA["day15"],
    "pHB": pHB["day15"],
    "pHC": pHC["day15"],
    "pHD": pHD["day15"],
    
    "ECA": ECA["day15"],
    "ECB": ECB["day15"],
    "ECC": ECC["day15"],
    "ECD": ECD["day15"],
    
    "DOA": DOA["day15"],
    "DOB": DOB["day15"],
    "DOC": DOC["day15"],
    "DOD": DOD["day15"],
    
    "BODA": BODA["day15"],
    "BODB": BODB["day15"],
    "BODC": BODC["day15"],
    "BODD": BODD["day15"],
    
    "TNA": TNA["day15"],
    "TNB": TNB["day15"],
    "TNC": TNC["day15"],
    "TND": TND["day15"],

})

range16 = pd.DataFrame(data={
    
    "TempA": tempA["day16"],
    "TempB": tempB["day16"],
    "TempC": tempC["day16"],
    "TempD": tempD["day16"],
    
    "pHA": pHA["day16"],
    "pHB": pHB["day16"],
    "pHC": pHC["day16"],
    "pHD": pHD["day16"],
    
    "ECA": ECA["day16"],
    "ECB": ECB["day16"],
    "ECC": ECC["day16"],
    "ECD": ECD["day16"],
    
    "DOA": DOA["day16"],
    "DOB": DOB["day16"],
    "DOC": DOC["day16"],
    "DOD": DOD["day16"],
    
    "BODA": BODA["day16"],
    "BODB": BODB["day16"],
    "BODC": BODC["day16"],
    "BODD": BODD["day16"],
    
    "TNA": TNA["day16"],
    "TNB": TNB["day16"],
    "TNC": TNC["day16"],
    "TND": TND["day16"],

})

range17 = pd.DataFrame(data={
    
    "TempA": tempA["day17"],
    "TempB": tempB["day17"],
    "TempC": tempC["day17"],
    "TempD": tempD["day17"],
    
    "pHA": pHA["day17"],
    "pHB": pHB["day17"],
    "pHC": pHC["day17"],
    "pHD": pHD["day17"],
    
    "ECA": ECA["day17"],
    "ECB": ECB["day17"],
    "ECC": ECC["day17"],
    "ECD": ECD["day17"],
    
    "DOA": DOA["day17"],
    "DOB": DOB["day17"],
    "DOC": DOC["day17"],
    "DOD": DOD["day17"],
    
    "BODA": BODA["day17"],
    "BODB": BODB["day17"],
    "BODC": BODC["day17"],
    "BODD": BODD["day17"],
    
    "TNA": TNA["day17"],
    "TNB": TNB["day17"],
    "TNC": TNC["day17"],
    "TND": TND["day17"],

})

range18 = pd.DataFrame(data={
    
    "TempA": tempA["day18"],
    "TempB": tempB["day18"],
    "TempC": tempC["day18"],
    "TempD": tempD["day18"],
    
    "pHA": pHA["day18"],
    "pHB": pHB["day18"],
    "pHC": pHC["day18"],
    "pHD": pHD["day18"],
    
    "ECA": ECA["day18"],
    "ECB": ECB["day18"],
    "ECC": ECC["day18"],
    "ECD": ECD["day18"],
    
    "DOA": DOA["day18"],
    "DOB": DOB["day18"],
    "DOC": DOC["day18"],
    "DOD": DOD["day18"],
    
    "BODA": BODA["day18"],
    "BODB": BODB["day18"],
    "BODC": BODC["day18"],
    "BODD": BODD["day18"],
    
    "TNA": TNA["day18"],
    "TNB": TNB["day18"],
    "TNC": TNC["day18"],
    "TND": TND["day18"],

})

range19 = pd.DataFrame(data={
    
    "TempA": tempA["day19"],
    "TempB": tempB["day19"],
    "TempC": tempC["day19"],
    "TempD": tempD["day19"],
    
    "pHA": pHA["day19"],
    "pHB": pHB["day19"],
    "pHC": pHC["day19"],
    "pHD": pHD["day19"],
    
    "ECA": ECA["day19"],
    "ECB": ECB["day19"],
    "ECC": ECC["day19"],
    "ECD": ECD["day19"],
    
    "DOA": DOA["day19"],
    "DOB": DOB["day19"],
    "DOC": DOC["day19"],
    "DOD": DOD["day19"],
    
    "BODA": BODA["day19"],
    "BODB": BODB["day19"],
    "BODC": BODC["day19"],
    "BODD": BODD["day19"],
    
    "TNA": TNA["day19"],
    "TNB": TNB["day19"],
    "TNC": TNC["day19"],
    "TND": TND["day19"],

})


range20 = pd.DataFrame(data={
    
    "TempA": tempA["day20"],
    "TempB": tempB["day20"],
    "TempC": tempC["day20"],
    "TempD": tempD["day20"],
    
    "pHA": pHA["day20"],
    "pHB": pHB["day20"],
    "pHC": pHC["day20"],
    "pHD": pHD["day20"],
    
    "ECA": ECA["day20"],
    "ECB": ECB["day20"],
    "ECC": ECC["day20"],
    "ECD": ECD["day20"],
    
    "DOA": DOA["day20"],
    "DOB": DOB["day20"],
    "DOC": DOC["day20"],
    "DOD": DOD["day20"],
    
    "BODA": BODA["day20"],
    "BODB": BODB["day20"],
    "BODC": BODC["day20"],
    "BODD": BODD["day20"],
    
    "TNA": TNA["day20"],
    "TNB": TNB["day20"],
    "TNC": TNC["day20"],
    "TND": TND["day20"],

})


range21 = pd.DataFrame(data={
    
    "TempA": tempA["day21"],
    "TempB": tempB["day21"],
    "TempC": tempC["day21"],
    "TempD": tempD["day21"],
    
    "pHA": pHA["day21"],
    "pHB": pHB["day21"],
    "pHC": pHC["day21"],
    "pHD": pHD["day21"],
    
    "ECA": ECA["day21"],
    "ECB": ECB["day21"],
    "ECC": ECC["day21"],
    "ECD": ECD["day21"],
    
    "DOA": DOA["day21"],
    "DOB": DOB["day21"],
    "DOC": DOC["day21"],
    "DOD": DOD["day21"],
    
    "BODA": BODA["day21"],
    "BODB": BODB["day21"],
    "BODC": BODC["day21"],
    "BODD": BODD["day21"],
    
    "TNA": TNA["day21"],
    "TNB": TNB["day21"],
    "TNC": TNC["day21"],
    "TND": TND["day21"],

})



range22 = pd.DataFrame(data={
    
    "TempA": tempA["day22"],
    "TempB": tempB["day22"],
    "TempC": tempC["day22"],
    "TempD": tempD["day22"],
    
    "pHA": pHA["day22"],
    "pHB": pHB["day22"],
    "pHC": pHC["day22"],
    "pHD": pHD["day22"],
    
    "ECA": ECA["day22"],
    "ECB": ECB["day22"],
    "ECC": ECC["day22"],
    "ECD": ECD["day22"],
    
    "DOA": DOA["day22"],
    "DOB": DOB["day22"],
    "DOC": DOC["day22"],
    "DOD": DOD["day22"],
    
    "BODA": BODA["day22"],
    "BODB": BODB["day22"],
    "BODC": BODC["day22"],
    "BODD": BODD["day22"],
    
    "TNA": TNA["day22"],
    "TNB": TNB["day22"],
    "TNC": TNC["day22"],
    "TND": TND["day22"],

})

In [154]:
range0

,TempA,TempB,TempC,TempD,pHA,pHB,pHC,pHD,ECA,ECB,...,DOC,DOD,BODA,BODB,BODC,BODD,TNA,TNB,TNC,TND
0,21.206192,21.100335,21.035532,20.751988,7.818671,8.084655,7.993220,8.441738,1765.471675,1690.184364,...,2.751422,2.641529,27.897203,27.621429,27.505181,27.864534,1.084703,1.196250,1.181199,1.193082
1,21.210902,20.935008,21.160186,21.168722,7.733693,8.062786,8.116770,8.454182,1768.496839,1680.426519,...,2.719459,2.610664,27.880118,27.247364,27.455165,27.706498,1.170497,1.237781,1.195217,1.229812
2,21.257416,20.941035,21.273460,21.197541,7.818443,8.087802,7.941933,8.358320,1776.482066,1697.319089,...,2.726032,2.665422,27.658382,27.319903,27.203856,27.151422,1.154327,1.216128,1.124503,1.123297
3,21.093705,21.186132,20.513038,20.812852,7.760058,8.106052,7.996784,8.478130,1822.128622,1692.445341,...,2.701371,2.684012,27.706219,27.315558,26.756316,27.191813,1.218249,1.177468,1.124602,1.125291
4,21.208442,20.867321,21.274380,21.217716,7.803024,8.112096,8.068508,8.444590,1829.976032,1686.100544,...,2.635958,2.624931,27.628345,27.344418,26.819442,27.063135,1.087334,1.204828,1.105554,1.110066
5,21.448270,20.946112,20.888478,21.144002,7.780396,8.077898,7.916353,8.411620,1830.120504,1695.631124,...,2.691764,2.675028,27.748257,27.542034,27.387916,27.057473,1.219095,1.102211,1.098171,1.235659
6,21.228977,21.051472,20.591673,21.221164,7.787964,8.091348,7.973434,8.375095,1748.267229,1686.946737,...,2.767117,2.613902,27.874668,27.677694,27.801593,27.278613,1.146284,1.223078,1.158676,1.112696
7,21.015192,21.048416,20.647787,21.195120,7.743336,8.063406,8.056185,8.468851,1818.277034,1682.436900,...,2.736630,2.664842,27.658636,27.234943,26.602975,27.510254,1.230245,1.238771,1.257891,1.242210
8,21.250331,20.910134,20.555041,20.871665,7.748731,8.069253,8.108102,8.413565,1792.678827,1696.318828,...,2.736455,2.692439,27.707285,27.496820,27.290348,27.371328,1.060629,1.189630,1.113790,1.138686
9,21.331754,21.019296,21.250167,21.122047,7.754750,8.110731,8.033576,8.446222,1819.034788,1686.296477,...,2.726824,2.654270,27.679131,27.466800,26.817564,27.522963,1.127325,1.125032,1.095986,1.143940
10,21.070343,20.966023,20.854593,20.952440,7.759525,8.112497,7.968768,8.451503,1798.328962,1690.052310,...,2.660341,2.695805,27.820207,27.476253,26.979680,27.755996,1.084578,1.103451,1.081400,1.158980
11,21.476953,20.900853,20.593728,20.765703,7.752960,8.099904,7.965583,8.471798,1792.022035,1689.275147,...,2.689275,2.607627,27.703297,27.445639,26.549581,27.553087,1.177475,1.165547,1.226685,1.269592
12,21.460124,20.832384,21.271612,21.119718,7.770882,8.105867,8.078701,8.358117,1803.450922,1694.558446,...,2.768522,2.641114,27.790418,27.445042,26.966435,27.162300,1.144762,1.246112,1.133958,1.139821
13,21.172848,20.941676,21.207334,21.259795,7.759083,8.060327,8.024973,8.476549,1791.859804,1691.654064,...,2.648625,2.630177,27.915685,27.319637,26.913554,27.336005,1.065599,1.231076,1.145886,1.207188
14,21.346331,21.194251,20.987291,20.707185,7.763947,8.108947,7.976323,8.451406,1769.948096,1679.336530,...,2.642291,2.699239,27.675193,27.319011,26.909249,27.472907,1.145441,1.150905,1.114234,1.171724

In [126]:
cols = df.columns

In [145]:
cols = ['Date', 'TempA', 'TempB', 'TempC', 'TempD', 'pHA', 'pHB', 'pHC', 'pHD',
       'ECA', 'ECB', 'ECC', 'ECD', 'DOA', 'DOB', 'DOC', 'DOD', 'BODA',
       'BODB', 'BODC', 'BODD', 'TNA', 'TNB', 'TNC', 'TND']

In [177]:
sample = pd.DataFrame(columns=cols)

In [178]:
sample

Empty DataFrame
Columns: [Date, TempA, TempB, TempC, TempD, pHA, pHB, pHC, pHD, ECA, ECB, ECC, ECD, DOA, DOB, DOC, DOD, BODA, BODB, BODC, BODD, TNA, TNB, TNC, TND]
Index: []

[0 rows x 25 columns]

In [181]:
df.columns = cols

In [182]:
a = df.iloc[0]
a

Date     15-Dec-21
TempA         21.5
TempB         21.2
TempC         21.3
TempD         21.4
pHA           7.73
pHB           8.12
pHC           7.91
pHD           8.48
ECA           1748
ECB           1679
ECC           1577
ECD           1695
DOA           2.55
DOB           2.62
DOC            2.6
DOD           2.59
BODA         27.96
BODB          27.7
BODC         27.88
BODD         27.93
TNA           1.28
TNB           1.25
TNC           1.26
TND           1.27
Name: 0, dtype: object

In [185]:
sample.append(a)

/tmp/ipykernel_4266/3583891468.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sample.append(a)

,Date,TempA,TempB,TempC,TempD,pHA,pHB,pHC,pHD,ECA,...,DOC,DOD,BODA,BODB,BODC,BODD,TNA,TNB,TNC,TND
0,15-Dec-21,21.5,21.2,21.3,21.4,7.73,8.12,7.91,8.48,1748,...,2.6,2.59,27.96,27.7,27.88,27.93,1.28,1.25,1.26,1.27

In [186]:
sample0 = sample.copy()

In [187]:
sample0.append(range0, ignore_index=True)

/tmp/ipykernel_4266/3925787615.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sample0.append(range0, ignore_index=True)

,Date,TempA,TempB,TempC,TempD,pHA,pHB,pHC,pHD,ECA,...,DOC,DOD,BODA,BODB,BODC,BODD,TNA,TNB,TNC,TND
0,NaN,21.206192,21.100335,21.035532,20.751988,7.818671,8.084655,7.99322,8.441738,1765.471675,...,2.751422,2.641529,27.897203,27.621429,27.505181,27.864534,1.084703,1.19625,1.181199,1.193082
1,NaN,21.210902,20.935008,21.160186,21.168722,7.733693,8.062786,8.11677,8.454182,1768.496839,...,2.719459,2.610664,27.880118,27.247364,27.455165,27.706498,1.170497,1.237781,1.195217,1.229812
2,NaN,21.257416,20.941035,21.27346,21.197541,7.818443,8.087802,7.941933,8.35832,1776.482066,...,2.726032,2.665422,27.658382,27.319903,27.203856,27.151422,1.154327,1.216128,1.124503,1.123297
3,NaN,21.093705,21.186132,20.513038,20.812852,7.760058,8.106052,7.996784,8.47813,1822.128622,...,2.701371,2.684012,27.706219,27.315558,26.756316,27.191813,1.218249,1.177468,1.124602,1.125291
4,NaN,21.208442,20.867321,21.27438,21.217716,7.803024,8.112096,8.068508,8.44459,1829.976032,...,2.635958,2.624931,27.628345,27.344418,26.819442,27.063135,1.087334,1.204828,1.105554,1.110066
5,NaN,21.44827,20.946112,20.888478,21.144002,7.780396,8.077898,7.916353,8.41162,1830.120504,...,2.691764,2.675028,27.748257,27.542034,27.387916,27.057473,1.219095,1.102211,1.098171,1.235659
6,NaN,21.228977,21.051472,20.591673,21.221164,7.787964,8.091348,7.973434,8.375095,1748.267229,...,2.767117,2.613902,27.874668,27.677694,27.801593,27.278613,1.146284,1.223078,1.158676,1.112696
7,NaN,21.015192,21.048416,20.647787,21.19512,7.743336,8.063406,8.056185,8.468851,1818.277034,...,2.73663,2.664842,27.658636,27.234943,26.602975,27.510254,1.230245,1.238771,1.257891,1.24221
8,NaN,21.250331,20.910134,20.555041,20.871665,7.748731,8.069253,8.108102,8.413565,1792.678827,...,2.736455,2.692439,27.707285,27.49682,27.290348,27.371328,1.060629,1.18963,1.11379,1.138686
9,NaN,21.331754,21.019296,21.250167,21.122047,7.75475,8.110731,8.033576,8.446222,1819.034788,...,2.726824,2.65427,27.679131,27.4668,26.817564,27.522963,1.127325,1.125032,1.095986,1.14394
10,NaN,21.070343,20.966023,20.854593,20.95244,7.759525,8.112497,7.968768,8.451503,1798.328962,...,2.660341,2.695805,27.820207,27.476253,26.97968,27.755996,1.084578,1.103451,1.0814,1.15898
11,NaN,21.476953,20.900853,20.593728,20.765703,7.75296,8.099904,7.965583,8.471798,1792.022035,...,2.689275,2.607627,27.703297,27.445639,26.549581,27.553087,1.177475,1.165547,1.226685,1.269592
12,NaN,21.460124,20.832384,21.271612,21.119718,7.770882,8.105867,8.078701,8.358117,1803.450922,...,2.768522,2.641114,27.790418,27.445042,26.966435,27.1623,1.144762,1.246112,1.133958,1.139821
13,NaN,21.172848,20.941676,21.207334,21.259795,7.759083,8.060327,8.024973,8.476549,1791.859804,...,2.648625,2.630177,27.915685,27.319637,26.913554,27.336005,1.065599,1.231076,1.145886,1.207188
14,NaN,21.346331,21.194251,20.987291,20.707185,7.763947,8.108947,7.976323,8.451406,1769.948096,...,2.642291,2.699239,27.675193,27.319011,26.909249,27.472907,1.145441,1.150905,1.114234,1.171724

In [9]:
date = datetime.datetime.strptime("15-12-2021", "%d-%m-%Y")
all_day = pd.date_range(date, periods=366)
all_day

DatetimeIndex(['2021-12-15', '2021-12-16', '2021-12-17', '2021-12-18',
               '2021-12-19', '2021-12-20', '2021-12-21', '2021-12-22',
               '2021-12-23', '2021-12-24',
               ...
               '2022-12-06', '2022-12-07', '2022-12-08', '2022-12-09',
               '2022-12-10', '2022-12-11', '2022-12-12', '2022-12-13',
               '2022-12-14', '2022-12-15'],
              dtype='datetime64[ns]', length=366, freq='D')

In [10]:
all_day = pd.DataFrame(all_day)

In [11]:
all_day.to_csv("350DaysDate.csv")

In [201]:
all_day

             0
0   2021-12-15
1   2021-12-16
2   2021-12-17
3   2021-12-18
4   2021-12-19
..         ...
345 2022-11-25
346 2022-11-26
347 2022-11-27
348 2022-11-28
349 2022-11-29

[350 rows x 1 columns]

In [194]:
range0

,TempA,TempB,TempC,TempD,pHA,pHB,pHC,pHD,ECA,ECB,...,DOC,DOD,BODA,BODB,BODC,BODD,TNA,TNB,TNC,TND
0,21.206192,21.100335,21.035532,20.751988,7.818671,8.084655,7.993220,8.441738,1765.471675,1690.184364,...,2.751422,2.641529,27.897203,27.621429,27.505181,27.864534,1.084703,1.196250,1.181199,1.193082
1,21.210902,20.935008,21.160186,21.168722,7.733693,8.062786,8.116770,8.454182,1768.496839,1680.426519,...,2.719459,2.610664,27.880118,27.247364,27.455165,27.706498,1.170497,1.237781,1.195217,1.229812
2,21.257416,20.941035,21.273460,21.197541,7.818443,8.087802,7.941933,8.358320,1776.482066,1697.319089,...,2.726032,2.665422,27.658382,27.319903,27.203856,27.151422,1.154327,1.216128,1.124503,1.123297
3,21.093705,21.186132,20.513038,20.812852,7.760058,8.106052,7.996784,8.478130,1822.128622,1692.445341,...,2.701371,2.684012,27.706219,27.315558,26.756316,27.191813,1.218249,1.177468,1.124602,1.125291
4,21.208442,20.867321,21.274380,21.217716,7.803024,8.112096,8.068508,8.444590,1829.976032,1686.100544,...,2.635958,2.624931,27.628345,27.344418,26.819442,27.063135,1.087334,1.204828,1.105554,1.110066
5,21.448270,20.946112,20.888478,21.144002,7.780396,8.077898,7.916353,8.411620,1830.120504,1695.631124,...,2.691764,2.675028,27.748257,27.542034,27.387916,27.057473,1.219095,1.102211,1.098171,1.235659
6,21.228977,21.051472,20.591673,21.221164,7.787964,8.091348,7.973434,8.375095,1748.267229,1686.946737,...,2.767117,2.613902,27.874668,27.677694,27.801593,27.278613,1.146284,1.223078,1.158676,1.112696
7,21.015192,21.048416,20.647787,21.195120,7.743336,8.063406,8.056185,8.468851,1818.277034,1682.436900,...,2.736630,2.664842,27.658636,27.234943,26.602975,27.510254,1.230245,1.238771,1.257891,1.242210
8,21.250331,20.910134,20.555041,20.871665,7.748731,8.069253,8.108102,8.413565,1792.678827,1696.318828,...,2.736455,2.692439,27.707285,27.496820,27.290348,27.371328,1.060629,1.189630,1.113790,1.138686
9,21.331754,21.019296,21.250167,21.122047,7.754750,8.110731,8.033576,8.446222,1819.034788,1686.296477,...,2.726824,2.654270,27.679131,27.466800,26.817564,27.522963,1.127325,1.125032,1.095986,1.143940
10,21.070343,20.966023,20.854593,20.952440,7.759525,8.112497,7.968768,8.451503,1798.328962,1690.052310,...,2.660341,2.695805,27.820207,27.476253,26.979680,27.755996,1.084578,1.103451,1.081400,1.158980
11,21.476953,20.900853,20.593728,20.765703,7.752960,8.099904,7.965583,8.471798,1792.022035,1689.275147,...,2.689275,2.607627,27.703297,27.445639,26.549581,27.553087,1.177475,1.165547,1.226685,1.269592
12,21.460124,20.832384,21.271612,21.119718,7.770882,8.105867,8.078701,8.358117,1803.450922,1694.558446,...,2.768522,2.641114,27.790418,27.445042,26.966435,27.162300,1.144762,1.246112,1.133958,1.139821
13,21.172848,20.941676,21.207334,21.259795,7.759083,8.060327,8.024973,8.476549,1791.859804,1691.654064,...,2.648625,2.630177,27.915685,27.319637,26.913554,27.336005,1.065599,1.231076,1.145886,1.207188
14,21.346331,21.194251,20.987291,20.707185,7.763947,8.108947,7.976323,8.451406,1769.948096,1679.336530,...,2.642291,2.699239,27.675193,27.319011,26.909249,27.472907,1.145441,1.150905,1.114234,1.171724

In [196]:
range0.to_csv("data/days/Day0.csv")
range1.to_csv("data/days/Day1.csv")
range2.to_csv("data/days/Day2.csv")
range3.to_csv("data/days/Day3.csv")
range4.to_csv("data/days/Day4.csv")
range5.to_csv("data/days/Day5.csv")
range6.to_csv("data/days/Day6.csv")
range7.to_csv("data/days/Day7.csv")
range8.to_csv("data/days/Day8.csv")
range9.to_csv("data/days/Day9.csv")
range10.to_csv("data/days/Day10.csv")
range11.to_csv("data/days/Day11.csv")
range12.to_csv("data/days/Day12.csv")
range13.to_csv("data/days/Day13.csv")
range14.to_csv("data/days/Day14.csv")
range15.to_csv("data/days/Day15.csv")
range16.to_csv("data/days/Day16.csv")
range17.to_csv("data/days/Day17.csv")
range18.to_csv("data/days/Day18.csv")
range19.to_csv("data/days/Day19.csv")
range20.to_csv("data/days/Day20.csv")
range21.to_csv("data/days/Day21.csv")
range22.to_csv("data/days/Day22.csv")

In [27]:
tempA = np.random.uniform(21.6,22 , 15)
tempB = np.random.uniform(21.2, 21.7 , 15)
tempC = np.random.uniform(21.1,21.9 , 15)
tempD = np.random.uniform(21.5, 21.8, 15)

pHA = np.random.uniform(7.69, 7.75 , 15)
pHB = np.random.uniform(7.95, 8.1 , 15)
pHC = np.random.uniform(7.68, 7.9 , 15)
pHD = np.random.uniform(8.11, 8.15 , 15)

ECA = np.random.uniform(1627, 1650, 15)
ECB = np.random.uniform(1676, 1690, 15)
ECC = np.random.uniform(1610, 1650, 15)
ECD = np.random.uniform(1690, 1705, 15)

DOA = np.random.uniform(2.41,2.45 , 15)
DOB = np.random.uniform(2.53,2.6 , 15)
DOC = np.random.uniform(2.49,2.52, 15)
DOD = np.random.uniform(2.5, 2.58, 15)

BODA = np.random.uniform(27.8,28.3 , 15)
BODB = np.random.uniform(27.5,28 , 15)
BODC = np.random.uniform(27.7,28.17 , 15)
BODD = np.random.uniform(27.7,28.14 , 15)

TNA = np.random.uniform(1.27, 1.31 , 15)
TNB = np.random.uniform(1.26 , 1.30, 15)
TNC = np.random.uniform(1.17 , 1.23, 15)
TND = np.random.uniform(1.29 , 1.34, 15)

In [28]:
range24 = pd.DataFrame(data={
    
    "TempA": tempA,
    "TempB": tempB,
    "TempC": tempC,
    "TempD": tempD,
    
    "pHA": pHA,
    "pHB": pHB,
    "pHC": pHC,
    "pHD": pHD,
    
    "ECA": ECA,
    "ECB": ECB,
    "ECC": ECC,
    "ECD": ECD,
    
    "DOA": DOA,
    "DOB": DOB,
    "DOC": DOC,
    "DOD": DOD,
    
    "BODA": BODA,
    "BODB": BODB,
    "BODC": BODC,
    "BODD": BODD,
    
    "TNA": TNA,
    "TNB": TNB,
    "TNC": TNC,
    "TND": TND,

})

In [29]:
range24

,TempA,TempB,TempC,TempD,pHA,pHB,pHC,pHD,ECA,ECB,...,DOC,DOD,BODA,BODB,BODC,BODD,TNA,TNB,TNC,TND
0,21.800380,21.588891,21.431331,21.674068,7.695580,8.056819,7.731145,8.120676,1642.505638,1678.853165,...,2.501876,2.503529,28.224653,27.646885,27.922627,28.081104,1.298105,1.271741,1.198534,1.332805
1,21.920235,21.248133,21.380457,21.622880,7.712974,8.041537,7.833355,8.115966,1637.729707,1679.791195,...,2.518077,2.543574,27.926674,27.991191,27.773546,27.920574,1.308063,1.293314,1.185767,1.324920
2,21.863995,21.491546,21.541366,21.578873,7.700187,8.074371,7.793505,8.126304,1645.406235,1687.053576,...,2.505997,2.521540,27.836356,27.617753,27.785447,27.765011,1.305349,1.294634,1.229676,1.294082
3,21.931220,21.629135,21.735895,21.545204,7.739543,8.080734,7.889516,8.143093,1635.421032,1676.562045,...,2.505629,2.542693,27.923391,27.707109,27.824692,28.050824,1.286594,1.273243,1.189800,1.326015
4,21.981116,21.341949,21.608124,21.545000,7.737124,7.997164,7.755385,8.142154,1631.081969,1678.055692,...,2.511977,2.525703,28.243569,27.659576,27.745612,27.750753,1.292608,1.277315,1.208213,1.305432
5,21.846276,21.454246,21.423953,21.554248,7.738150,8.095599,7.870155,8.128861,1638.575048,1679.411477,...,2.506881,2.541795,28.296648,27.542598,27.813365,28.125892,1.309775,1.286161,1.177041,1.294216
6,21.913429,21.652317,21.744931,21.697999,7.700908,8.030211,7.806385,8.121617,1634.110996,1681.305955,...,2.500111,2.500425,28.170132,27.753417,28.101514,27.750608,1.279960,1.271798,1.171392,1.339100
7,21.989238,21.399812,21.560160,21.551050,7.702410,8.044477,7.771116,8.123361,1649.866697,1683.439556,...,2.517952,2.522571,28.127433,27.863189,27.986701,27.857576,1.308441,1.263582,1.201070,1.322896
8,21.625402,21.271953,21.299290,21.533548,7.724137,7.977696,7.788280,8.121541,1646.703678,1687.317109,...,2.490601,2.525854,27.897353,27.607439,28.000052,27.720726,1.294531,1.297136,1.191351,1.294335
9,21.700084,21.442542,21.100646,21.579922,7.711304,7.978739,7.711859,8.146430,1642.279787,1676.612356,...,2.510631,2.526487,27.900982,27.558032,27.830261,27.902363,1.275698,1.279905,1.180145,1.305626
10,21.859082,21.307084,21.515496,21.794283,7.718914,7.973155,7.775976,8.147016,1639.575336,1688.074908,...,2.512405,2.538242,28.188417,27.731914,28.136344,28.110737,1.287643,1.285699,1.188900,1.334676
11,21.668078,21.416439,21.251597,21.789767,7.736714,8.070128,7.853656,8.143443,1649.497628,1688.954237,...,2.493236,2.500073,28.120167,27.749315,28.015301,28.057013,1.306629,1.268112,1.198974,1.302104
12,21.659254,21.476769,21.820747,21.567458,7.718413,8.093637,7.709191,8.140356,1645.281896,1687.240346,...,2.501148,2.511491,27.889022,27.725140,27.835323,27.982864,1.270522,1.270883,1.225339,1.310075
13,21.746538,21.506351,21.690682,21.748841,7.722175,8.018821,7.814807,8.117507,1636.254243,1689.128161,...,2.495282,2.545457,28.240856,27.796908,27.782170,27.923744,1.289316,1.281889,1.218123,1.319585
14,21.930500,21.313103,21.278286,21.672078,7.732669,7.984925,7.831165,8.144355,1643.049617,1683.387663,...,2.503744,2.557333,27.844773,27.996878,27.719815,28.120561,1.291307,1.284647,1.200794,1.339393

In [30]:
range24.to_csv("data/days/day24.csv")